from share.provider import OAIProviderAppConfig


class AppConfig(OAIProviderAppConfig):
    name = 'providers.edu.pdxscholar'
    version = '0.0.1'
    title = 'pdxscholar'
    long_title = 'PDXScholar Portland State University'
    home_page = 'http://pdxscholar.library.pdx.edu'
    url = 'http://pdxscholar.library.pdx.edu/do/oai/'
    approved_sets = [
        'actg',
        'actg_fac',
        'anth_fac',
        'anthos',
        'anthos_archives',
        'ling_fac',
        'bio_fac',
        'eng_bookpubpaper',
        'busadmin_fac',
        'childfamily_pub',
        'centerforlakes_pub',
        'clee_pubs',
        'publicservice_pub',
        'realestate_pub',
        'scienceeducation_fac',
        'chem_fac',
        'chla_fac',
        'cengin_fac',
        'cengin_gradprojects',
        'cengin_honorstheses',
        'comm_fac',
        'commhealth_fac',
        'compsci_fac',
        'coun_fac',
        'ccj_fac',
        'ccj_capstone',
        'ci_fac',
        'etds',
        'open_access_etds',
        'econ_fac',
        'edu_fac',
        'elp_fac',
        'ece_fac',
        'etm_fac',
        'esm_fac',
        'geog_fac',
        'geog_masterpapers',
        'geology_fac',
        'hist_fac',
        'naturalresources_pub',
        'iss_pub',
        'metropolitianstudies',
        'aging_pub',
        'is_fac',
        'lse_comp',
        'ulib_fac',
        'lltr',
        'mem_gradprojects',
        'usp_murp',
        'mth_fac',
        'mengin_fac',
        'metroscape',
        'pdxopen',
        'mcnair',
        'phl_fac',
        'phy_fac',
        'prc',
        'psy_fac',
        'pubadmin_fac',
        'realestate_workshop',
        'usp_planning',
        'rri_facpubs',
        'socwork_fac',
        'soc_fac',
        'sped_fac',
        'sphr_fac',
        'sysc_fac',
        'honorstheses',
        'usp_fac',
        'wgss_fac',
        'wll_fac',
        'younghistorians',
    ]
    property_list = []
