# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 15:14
from __future__ import unicode_literals

from django.db import migrations
import share.robot


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=share.robot.RobotUserMigration('cy.ac.cut'),
        ),
        migrations.RunPython(
            code=share.robot.RobotOauthTokenMigration('cy.ac.cut'),
        ),
        migrations.RunPython(
            code=share.robot.RobotScheduleMigration('cy.ac.cut'),
        ),
    ]
