# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 14:58
from __future__ import unicode_literals

from django.db import migrations
import share.robot


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('share', '0041_shareuser_is_trusted'),
    ]

    operations = [
        migrations.RunPython(
            code=share.robot.RobotUserMigration('edu.wm'),
        ),
        migrations.RunPython(
            code=share.robot.RobotOauthTokenMigration('edu.wm'),
        ),
        migrations.RunPython(
            code=share.robot.RobotScheduleMigration('edu.wm'),
        ),
    ]
