# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.6"

cache:
    directories:
      - $HOME/.cache

dist: trusty

env:
  global:
    - ES_JAVA_OPTS="-Xms512m -Xmx512m"
    - PROJECT_DIR="$PWD"
    - WHEELHOUSE="$HOME/.cache/wheelhouse"

before_install:
    # cache directories
    - |
      mkdir -p $HOME/.cache/downloads
      mkdir -p $HOME/.cache/pip
      mkdir -p $HOME/.cache/wheelhouse
    # eleasticsearch
    - |
      curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0-amd64.deb -o elasticsearch.deb
      sudo dpkg -i --force-confnew elasticsearch.deb
      sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
      sudo service elasticsearch restart

services:
  - postgresql
  - elasticsearch

addons:
  postgresql: "9.5"

install:
    - cd $PROJECT_DIR
    - travis_retry pip install --upgrade pip
    - travis_retry pip install flake8==3.8.3 --force-reinstall --upgrade
    - travis_retry pip install -r dev-requirements.txt
    - travis_retry pip install .

before_script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200

# Run Python tests and flake8
script:
    - flake8 .
    - py.test tests --cov=share --cov=api
    - coverage run --append --source=share,api -m behave

after_success:
    - coveralls
