# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.5"

sudo: false

cache:
    directories:
      - node_modules

addons:
    postgresql: "9.4"

install:
    - travis_retry pip install --upgrade pip
    - travis_retry pip install flake8==2.4.0 --force-reinstall --upgrade
    - travis_retry pip install -r dev-requirements.txt

# Run Python tests and flake8
script:
    - flake8 .
    - py.test tests
