# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 22:18
from __future__ import unicode_literals

from django.db import migrations
import share.core.provider


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=share.core.provider.ProviderSourceMigration('figshare'),
        ),
        migrations.RunPython(
            code=share.core.provider.HarvesterScheduleMigration('figshare'),
        ),
        migrations.RunPython(
            code=share.core.provider.NormalizerScheduleMigration('figshare'),
        ),
    ]
