# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 15:49
from __future__ import unicode_literals

from django.db import migrations
import share.robot


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=share.robot.RobotUserMigration('edu.jmu'),
        ),
        migrations.RunPython(
            code=share.robot.RobotOauthTokenMigration('edu.jmu'),
        ),
        migrations.RunPython(
            code=share.robot.RobotScheduleMigration('edu.jmu'),
        ),
    ]
