from unittest import mock

import pytest
from lxml import etree


NAMESPACES = {'atom': 'http://www.w3.org/2005/Atom'}


# TODO add tests for RSS


@pytest.mark.django_db
class TestFeed:

    @pytest.fixture()
    def fake_items(self):
        with mock.patch('api.views.feeds.index_strategy.get_strategy_for_sharev2_search') as mock_get_for_searching:
            mock_strategy = mock_get_for_searching.return_value
            mock_strategy.pls_handle_search__passthru.return_value = {
                'hits': {
                    'hits': [
                        {'_source': item, '_id': item['id']}
                        for item in _FAKE_ITEMS
                    ],
                },
            }
            yield _FAKE_ITEMS

    def test_atom(self, client, fake_items):
        resp = client.get('/api/v2/feeds/atom')
        assert resp.status_code == 200
        feed = etree.fromstring(resp.content)
        assert len(feed.xpath('//atom:entry', namespaces=NAMESPACES)) == 11
        assert feed.nsmap == {None: 'http://www.w3.org/2005/Atom'}
        assert feed.getchildren()[0].text.startswith('SHARE: Atom feed for query:')
        expected_titles = set(
            item['title']
            for item in fake_items
        )
        actual_titles = set(
            element.text
            for element in feed.xpath('//atom:entry/atom:title', namespaces=NAMESPACES)
        )
        assert actual_titles == expected_titles
        assert len(actual_titles) == 11

    def test_gone(self, client, fake_items):
        for feed_url, expected_status in (
            ('/api/v2/atom/', 410),
            ('/api/v2/rss/', 410),
            ('/api/v2/feeds/atom/', 200),
            ('/api/v2/feeds/rss/', 200),
        ):
            resp = client.get(feed_url)
            assert resp.status_code == expected_status


_FAKE_ITEMS = [
    {
        "id": "2011F-F56-334",
        "sources": ["Why hospital international impact car.22"],
        "source_config": "Option appear him.",
        "source_unique_id": "Family measure once seat religious.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.517102+00:00",
        "date_modified": "2025-03-05T19:52:17.529787+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 0",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
    {
        "id": "201FE-A32-223",
        "sources": ["Record material white piece.24"],
        "source_config": "Tell around benefit receive this.",
        "source_unique_id": "Seven color six society daughter home born.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.552298+00:00",
        "date_modified": "2025-03-05T19:52:17.563387+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 1",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
    {
        "id": "20089-44F-D12",
        "sources": ["Learn its quickly while develop traditional politics office.26"],
        "source_config": "To another series better need away.",
        "source_unique_id": "Lot popular energy worry up group company medical.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.590476+00:00",
        "date_modified": "2025-03-05T19:52:17.602544+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 2",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
    {
        "id": "20167-F2B-C01",
        "sources": ["Must else live my toward eight we major.28"],
        "source_config": "Weight hand without through sure.",
        "source_unique_id": "Develop join the listen crime war.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.631057+00:00",
        "date_modified": "2025-03-05T19:52:17.644379+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 3",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
    {
        "id": "20246-A07-AF0",
        "sources": ["Street alone truth Mr still bar.30"],
        "source_config": "Few water matter here miss bag defense.",
        "source_unique_id": "Reduce personal begin series bank movement.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.669044+00:00",
        "date_modified": "2025-03-05T19:52:17.681888+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 4",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
    {
        "id": "200D1-425-5DF",
        "sources": ["Level threat culture think guy success join.32"],
        "source_config": "Before stay travel outside event walk.",
        "source_unique_id": "Group learn public common some very big.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.704433+00:00",
        "date_modified": "2025-03-05T19:52:17.717365+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 5",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
    {
        "id": "201AF-F01-4CE",
        "sources": ["Back heavy animal.34"],
        "source_config": "Direction east certainly we bring blue wide.",
        "source_unique_id": "Measure field year its.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.740574+00:00",
        "date_modified": "2025-03-05T19:52:17.754145+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 6",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
    {
        "id": "2003A-91E-FBD",
        "sources": ["Hope outside cup follow nearly natural.36"],
        "source_config": "Hotel study team imagine raise raise.",
        "source_unique_id": "Time reduce speak child.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.780641+00:00",
        "date_modified": "2025-03-05T19:52:17.797155+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 7",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
    {
        "id": "20119-3FA-EAC",
        "sources": ["Subject manage trip address.38"],
        "source_config": "Food fly raise drop though ask.",
        "source_unique_id": "Know reach image town.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.824233+00:00",
        "date_modified": "2025-03-05T19:52:17.836944+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 8",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
    {
        "id": "201F7-ED6-D9B",
        "sources": ["Senior think myself between travel get cut.40"],
        "source_config": "Amount word something long on alone level.",
        "source_unique_id": "Operation kind which.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.859089+00:00",
        "date_modified": "2025-03-05T19:52:17.871550+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 9",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
    {
        "id": "20082-8F4-88A",
        "sources": ["Size alone raise draw ok common.42"],
        "source_config": "Writer two source newspaper bank lot figure.",
        "source_unique_id": "Civil bill imagine finally.",
        "type": "creative work",
        "types": ["creative work"],
        "date_created": "2025-03-05T19:52:17.895226+00:00",
        "date_modified": "2025-03-05T19:52:17.908008+00:00",
        "date_published": "2007-02-16T03:39:48Z",
        "date_updated": "2003-09-12T09:37:20Z",
        "description": "Discover pattern family ok face. Security whom during attention set political cell bad.",
        "language": "sd",
        "retracted": False,
        "title": "my fabulous work 10",
        "date": "2007-02-16T03:39:48Z",
        "affiliations": [],
        "contributors": ["Mcgee-Zimmerman", "Young, Hall and Jensen"],
        "funders": [],
        "publishers": [],
        "hosts": [],
        "identifiers": ["http://wagner.com/"],
        "tags": [],
        "subjects": [],
        "subject_synonyms": [],
        "lists": {
            "affiliations": [],
            "contributors": [
                {
                    "type": "institution",
                    "types": ["institution", "organization", "agent"],
                    "name": "Mcgee-Zimmerman",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Mcgee-Zimmerman",
                },
                {
                    "type": "organization",
                    "types": ["organization", "agent"],
                    "name": "Young, Hall and Jensen",
                    "identifiers": [],
                    "relation": "creator",
                    "cited_as": "Young, Hall and Jensen",
                },
            ],
            "funders": [],
            "publishers": [],
            "hosts": [],
            "lineage": [],
        },
    },
]
