# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 14:39
from __future__ import unicode_literals

from django.db import migrations
import share.robot


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=share.robot.RobotUserMigration('fr.archives-ouvertes.hal'),
        ),
        migrations.RunPython(
            code=share.robot.RobotOauthTokenMigration('fr.archives-ouvertes.hal'),
        ),
        migrations.RunPython(
            code=share.robot.RobotScheduleMigration('fr.archives-ouvertes.hal'),
        ),
    ]
