# Generated by Django 3.2.5 on 2023-07-11 15:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import trove.models.resource_identifier
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('share', '0069_rawdatum_mediatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedIndexcardRdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('turtle_checksum_iri', models.TextField(db_index=True)),
                ('focus_iri', models.TextField()),
                ('rdf_as_turtle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DerivedIndexcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('derived_checksum_iri', models.TextField()),
                ('derived_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Indexcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatestIndexcardRdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('turtle_checksum_iri', models.TextField(db_index=True)),
                ('focus_iri', models.TextField()),
                ('rdf_as_turtle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sufficiently_unique_iri', models.TextField(unique=True, validators=[trove.models.resource_identifier.validate_sufficiently_unique_iri])),
                ('scheme_list', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(validators=[trove.models.resource_identifier.validate_iri_scheme]), size=None)),
            ],
        ),
        migrations.AddConstraint(
            model_name='resourceidentifier',
            constraint=models.CheckConstraint(check=models.Q(('sufficiently_unique_iri__contains', ':'), models.Q(models.Q(('scheme_list__len__gt', 0), ('sufficiently_unique_iri__startswith', '://')), ('scheme_list', [django.db.models.functions.text.Substr('sufficiently_unique_iri', 1, django.db.models.expressions.CombinedExpression(django.db.models.functions.text.StrIndex('sufficiently_unique_iri', django.db.models.expressions.Value(':')), '-', django.db.models.expressions.Value(1)))]), _connector='OR')), name='trove_resourceidentifier_suffuniq_iri_matches_scheme_list'),
        ),
        migrations.AddField(
            model_name='latestindexcardrdf',
            name='from_raw_datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.rawdatum'),
        ),
        migrations.AddField(
            model_name='latestindexcardrdf',
            name='indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trove.indexcard'),
        ),
        migrations.AddField(
            model_name='indexcard',
            name='focus_identifier_set',
            field=models.ManyToManyField(related_name='indexcard_set', to='trove.ResourceIdentifier'),
        ),
        migrations.AddField(
            model_name='indexcard',
            name='focustype_identifier_set',
            field=models.ManyToManyField(related_name='_trove_indexcard_focustype_identifier_set_+', to='trove.ResourceIdentifier'),
        ),
        migrations.AddField(
            model_name='indexcard',
            name='source_record_suid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexcard_set', to='share.sourceuniqueidentifier'),
        ),
        migrations.AddField(
            model_name='derivedindexcard',
            name='deriver_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trove.resourceidentifier'),
        ),
        migrations.AddField(
            model_name='derivedindexcard',
            name='upriver_indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trove.indexcard'),
        ),
        migrations.AddField(
            model_name='archivedindexcardrdf',
            name='from_raw_datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.rawdatum'),
        ),
        migrations.AddField(
            model_name='archivedindexcardrdf',
            name='indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trove.indexcard'),
        ),
        migrations.AddConstraint(
            model_name='latestindexcardrdf',
            constraint=models.UniqueConstraint(fields=('indexcard',), name='trove_latestindexcardrdf_uniq_indexcard'),
        ),
        migrations.AddConstraint(
            model_name='derivedindexcard',
            constraint=models.UniqueConstraint(fields=('upriver_indexcard', 'deriver_identifier'), name='trove_derivedindexcard_upriverindexcard_deriveridentifier'),
        ),
        migrations.AddConstraint(
            model_name='archivedindexcardrdf',
            constraint=models.UniqueConstraint(fields=('indexcard', 'from_raw_datum', 'turtle_checksum_iri'), name='trove_archivedindexcardrdf_uniq_archived_version'),
        ),
    ]
