# Generated by Django 3.2.5 on 2023-06-30 16:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import trove.models.persistent_iri


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('share', '0069_rawdatum_mediatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedIndexcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('card_as_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersistentIri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sufficiently_unique_iri', models.TextField(unique=True, validators=[trove.models.persistent_iri.validate_sufficiently_unique_iri])),
                ('scheme_list', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(validators=[trove.models.persistent_iri.validate_iri_scheme]), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RdfIndexcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('focus_iri', models.TextField()),
                ('card_as_turtle', models.TextField()),
                ('focus_piri_set', models.ManyToManyField(related_name='rdf_indexcard_set', to='trove.PersistentIri')),
                ('focustype_piri_set', models.ManyToManyField(related_name='_trove_rdfindexcard_focustype_piri_set_+', to='trove.PersistentIri')),
                ('from_raw_datum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdf_indexcard_set', to='share.rawdatum')),
            ],
        ),
        migrations.AddConstraint(
            model_name='persistentiri',
            constraint=models.CheckConstraint(check=models.Q(('sufficiently_unique_iri__contains', ':'), models.Q(models.Q(('scheme_list__len__gt', 0), ('sufficiently_unique_iri__startswith', '://')), ('scheme_list', [django.db.models.functions.text.Substr('sufficiently_unique_iri', 1, django.db.models.expressions.CombinedExpression(django.db.models.functions.text.StrIndex('sufficiently_unique_iri', django.db.models.expressions.Value(':')), '-', django.db.models.expressions.Value(1)))]), _connector='OR')), name='trove_persistentiri_suffuniq_iri_matches_scheme_list'),
        ),
        migrations.AddField(
            model_name='derivedindexcard',
            name='deriver_piri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trove.persistentiri'),
        ),
        migrations.AddField(
            model_name='derivedindexcard',
            name='upriver_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trove.rdfindexcard'),
        ),
        migrations.AddConstraint(
            model_name='rdfindexcard',
            constraint=models.UniqueConstraint(fields=('from_raw_datum', 'focus_iri'), name='trove_rdfindexcard_rawdatum_focusiri'),
        ),
        migrations.AddConstraint(
            model_name='derivedindexcard',
            constraint=models.UniqueConstraint(fields=('upriver_card', 'deriver_piri'), name='trove_derivedindexcard_uprivercard_deriverpiri'),
        ),
    ]
