# Generated by Django 3.2.5 on 2023-07-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trove', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcard',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
