# Generated by Django 3.2.5 on 2023-08-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trove', '0003_resourceidentifier_raw_iri_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedindexcardrdf',
            name='indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trove_archivedindexcardrdf_set', to='trove.indexcard'),
        ),
        migrations.AlterField(
            model_name='latestindexcardrdf',
            name='indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trove_latestindexcardrdf_set', to='trove.indexcard'),
        ),
    ]
