# Generated by Django 3.2.25 on 2024-05-21 19:11

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False  # allow adding indexes concurrently (without locking tables)

    dependencies = [
        ('trove', '0004_auto_20230804_2021'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='indexcard',
            index=models.Index(fields=['deleted'], name='trove_index_deleted_bcffde_idx'),
        ),
        AddIndexConcurrently(
            model_name='latestindexcardrdf',
            index=models.Index(fields=['modified'], name='trove_lates_modifie_c6b0b1_idx'),
        ),
    ]
