# Generated by Django 3.2.25 on 2024-09-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0074_sourceuniqueidentifier_is_supplementary'),
        ('trove', '0005_indexes_for_oaipmh'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementaryIndexcardRdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('turtle_checksum_iri', models.TextField(db_index=True)),
                ('focus_iri', models.TextField()),
                ('rdf_as_turtle', models.TextField()),
                ('from_raw_datum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.rawdatum')),
                ('indexcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trove_supplementaryindexcardrdf_set', to='trove.indexcard')),
                ('supplementary_suid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_rdf_set', to='share.sourceuniqueidentifier')),
            ],
        ),
        migrations.AddConstraint(
            model_name='supplementaryindexcardrdf',
            constraint=models.UniqueConstraint(fields=('indexcard', 'supplementary_suid'), name='trove_supplementaryindexcardrdf_uniq_supplement'),
        ),
    ]
