# Generated by Django 5.1.7 on 2025-03-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trove', '0006_supplementary_indexcard_rdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedindexcardrdf',
            name='indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='trove.indexcard'),
        ),
        migrations.AlterField(
            model_name='indexcard',
            name='focustype_identifier_set',
            field=models.ManyToManyField(related_name='+', to='trove.resourceidentifier'),
        ),
        migrations.AlterField(
            model_name='latestindexcardrdf',
            name='indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='trove.indexcard'),
        ),
        migrations.AlterField(
            model_name='supplementaryindexcardrdf',
            name='indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='trove.indexcard'),
        ),
    ]
