# Generated by Django 3.2.25 on 2025-04-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0077_big_cleanup_2025'),
        ('trove', '0006_supplementary_indexcard_rdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedindexcardrdf',
            name='from_raw_datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='share.rawdatum'),
        ),
        migrations.AlterField(
            model_name='latestindexcardrdf',
            name='from_raw_datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='share.rawdatum'),
        ),
        migrations.AlterField(
            model_name='supplementaryindexcardrdf',
            name='from_raw_datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='share.rawdatum'),
        ),
    ]
