# Generated by Django 5.2.3 on 2025-06-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trove', '0010_resource_description_rename'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='latestresourcedescription',
            new_name='trove_lates_modifie_418889_idx',
            old_name='trove_lates_modifie_c6b0b1_idx',
        ),
        migrations.RenameIndex(
            model_name='latestresourcedescription',
            new_name='trove_lates_expirat_70dd04_idx',
            old_name='trove_lates_expirat_92ac89_idx',
        ),
        migrations.RenameIndex(
            model_name='supplementaryresourcedescription',
            new_name='trove_suppl_expirat_3cb612_idx',
            old_name='trove_suppl_expirat_3ea6e1_idx',
        ),
        migrations.AlterField(
            model_name='archivedresourcedescription',
            name='indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='trove.indexcard'),
        ),
        migrations.AlterField(
            model_name='indexcard',
            name='focustype_identifier_set',
            field=models.ManyToManyField(related_name='+', to='trove.resourceidentifier'),
        ),
        migrations.AlterField(
            model_name='latestresourcedescription',
            name='indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='trove.indexcard'),
        ),
        migrations.AlterField(
            model_name='supplementaryresourcedescription',
            name='indexcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='trove.indexcard'),
        ),
    ]
