# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 19:29
from __future__ import unicode_literals

from django.db import migrations
import share.robot


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=share.robot.RobotUserMigration('info.ssoar'),
        ),
        migrations.RunPython(
            code=share.robot.RobotOauthTokenMigration('info.ssoar'),
        ),
        migrations.RunPython(
            code=share.robot.RobotScheduleMigration('info.ssoar'),
        ),
    ]
