# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 19:22
from __future__ import unicode_literals

from django.db import migrations
# import share.robot


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM django_migrations WHERE app='autocurateperson';"
        ),
        migrations.RunSQL(
            "UPDATE share_shareuser SET username='bots.autocurate.person', robot='bots.autocurate.person' WHERE username='bots.autocurateperson';"
        ),
        migrations.RunSQL(
            "UPDATE djcelery_periodictask SET name='autocurate.person bot task', args='[\"bots.autocurate.person\"]' WHERE name='autocurateperson bot task';"
        ),
        # migrations.RunPython(
        #     code=share.robot.RobotUserMigration('autocurate.person'),
        # ),
        # migrations.RunPython(
        #     code=share.robot.RobotOauthTokenMigration('autocurate.person'),
        # ),
        # migrations.RunPython(
        #     code=share.robot.RobotScheduleMigration('autocurate.person'),
        # ),
    ]
