# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org.zenodo', '0002_favicon'),
        ('org.zenodo', '0002_disable'),
    ]

    operations = [
    ]
