from share.provider import OAIProviderAppConfig


class AppConfig(OAIProviderAppConfig):
    name = 'providers.edu.utktrace'
    version = '0.0.1'
    title = 'utktrace'
    long_title = 'Trace: Tennessee Research and Creative Exchange'
    home_page = 'http://trace.tennessee.edu'
    url = 'http://trace.tennessee.edu/do/oai/'
    approved_sets = [
        'utk_accopubs',
        'utk_agrieconpubs',
        'utk_animpubs',
        'utk_anthpubs',
        'utk_architecpubs',
        'utk_audipubs',
        'utk_aviapubs',
        'utk_biocpubs',
        'utk_compmedpubs',
        'utk_biospubs',
        'utk_botapubs',
        'utk_statpubs',
        'utk_cssjpapers',
        'catalyst',
        'utk_chembiopubs',
        'utk_chempubs',
        'utk_chilpubs',
        'utk_civipubs',
        'utk_claspubs',
        'utk_lawpubl',
        'utk-lawjournals',
        'utk_compmatdata',
        'utk_datasets',
        'utk_davisbacon',
        'utk_rotcarmypubs',
        'utk_biolpubs',
        'utk_eartpubs',
        'utk_ecolpubs',
        'utk_econpubs',
        'utk_edleadpubs',
        'utk_educpubs',
        'utk_elecutsipubs',
        'utk_englpubs',
        'utk_entopubs',
        'utk_compmedpeer',
        'utk_smalpeer',
        'utk_largpeer',
        'utk_famipubs',
        'utk_foodpubs',
        'utk_forepubs',
        'gamut',
        'utk_geno',
        'utk_indupubs',
        'utk_induengipubs',
        'utk_nuclearpubs',
        'utk_instpubs',
        'utk_intepubs',
        'ijns',
        'utk_exerpubs',
        'utk_largpubs',
        'utk_latipubs',
        'utk_mtaspubs',
        'utk_manapubs',
        'utk_markpubs',
        'utk_matepubs',
        'utk_mathutsipubs',
        'utk_mechutsipubs',
        'utk_micrpubs',
        'utk_modepubs',
        'utk_molecularsimulation',
        'utk_nuclpubs',
        'utk_libfac',
        'utk_artfac',
        'utk_artpeer',
        'utk_libpub',
        'utk_physastrpubs',
        'utk_psycpubs',
        'utk_bakecentpubs',
        'pursuit',
        'utk_relipubs',
        'utk_infosciepubs',
        'utk_jourpubs',
        'utk_socipubs',
        'utk_socopubs',
        'rgsj',
        'jaepl',
        'utk_theapubs',
        'utk_theopubs',
        'utgradmedpubs',
        'vernacular',
    ]
    property_list = ['date', 'source', 'identifier', 'type', 'format', 'setSpec']
