from share.provider import OAIProviderAppConfig


class AppConfig(OAIProviderAppConfig):
    name = 'providers.edu.iwu_commons'
    version = '0.0.1'
    title = 'iwu_commons'
    long_title = 'Digital Commons @ Illinois Wesleyan University'
    home_page = 'http://digitalcommons.iwu.edu'
    url = 'http://digitalcommons.iwu.edu/do/oai/'
    approved_sets = [
        'oral_hist',
        'ames_award',
        'arthonors_book_gallery',
        'arthonors',
        'bio',
        'music_compositions',
        'cs',
        'constructing',
        'economics',
        'education',
        'ed_studies_posters',
        'eng',
        'envstu',
        'fac_biennial_exhibit_all',
        'fac_biennial_exhibit2011',
        'fac_biennial_exhibit2013',
        'fac_biennial_exhibit',
        'firstyear_summer',
        'founders_day_docs',
        'german',
        'theatre_hist',
        'history',
        'teaching_excellence',
        'honors_docs',
        'honors_programs_docs',
        'physics_honproj',
        'bio_honproj',
        'intstu_honproj',
        'envstu_honproj',
        'russian_honproj',
        'history_honproj',
        'theatre_honproj',
        'religion_honproj',
        'wostu_honproj',
        'nursing_honproj',
        'education_honproj',
        'eng_honproj',
        'french_honproj',
        'math_honproj',
        'socanth_honproj',
        'econ_honproj',
        'art_honproj',
        'cs_honproj',
        'amstudies_honproj',
        'grs_honproj',
        'hispstu_honproj',
        'polisci_honproj',
        'chem_honproj',
        'phil_honproj',
        'acct_fin_honproj',
        'busadmin_honproj',
        'german_honproj',
        'psych_honproj',
        'bookshelf',
        'wglt_interviews',
        'oralhist_2009',
        'oralhist_ucd',
        'oralhist_wesn',
        'italian',
        'japanese',
        'jwprc',
        'math',
        'music',
        'nursing',
        'oralhistory',
        'oralhistory_gallery',
        'anth_ethno',
        'gateway',
        'envstu_seminar',
        'music_outstanding_works',
        'writing_student',
        'polsci',
        'psych',
        'religion',
        'respublica',
        'russian',
        'grs_scholarship',
        'math_scholarship',
        'nursing_scholarship',
        'bio_scholarship',
        'religion_scholarship',
        'mcll_scholarship',
        'envstu_scholarship',
        'physics_scholarship',
        'socanth_scholarship',
        'history_scholarship',
        'intstu_scholarship',
        'cs_scholarship',
        'chem_scholarship',
        'eng_scholarship',
        'hispstu_scholarship',
        'psych_scholarship',
        'socanth',
        'student_prof',
        'sea',
        'parkplace',
        'uer',
        'germanresearch',
        'uauje',
        'univcom',
        'wglt',
    ]
    property_list = []
