FIELDS = {
    'uin': 'field_21',
    'registration date': 'field_2',
    'title': 'field_7',
    'questions and objectives': 'field_75',
    'summary': 'field_78',
    'study type': 'field_72',
    'study type other': 'field_14',
    'primary investigator': 'field_3',
    'other investigators': 'field_4',
    'additional investigators': 'field_94',
    'contact details': 'field_5',
    'email': 'field_97',
    'participating institutions': 'field_68',
    'countries of recruitment': 'field_10',
    'funders': 'field_9',
    'health conditions or problems studied': 'field_11',
    'patient population': 'field_29',
    'interventions': 'field_12',
    'inclusion criteria': 'field_13',
    'exclusion criteria': 'field_70',
    'control or comparators': 'field_28',
    'primary outcomes': 'field_18',
    'key secondary outcomes': 'field_19',
    'target sample size': 'field_16',
    'recruitment status': 'field_79',
    'other recruitment status': 'field_17',
    'first enrollment date': 'field_15',
    'expected enrollment completion date': 'field_80',
    'expected research completion date': 'field_73',
    'ethical approval': 'field_81',
    'ethical approval details': 'field_63',
    'ethical committee judgment': 'field_62',
    'data': 'field_64',
    'published paper identifier': 'field_37',
    'study website': 'field_30',
    'study results': 'field_89'
}

