# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_create_share_user'),
    ]

<<<<<<< HEAD
=======
    # Meant to be run on an empty database, so don't worry about existing duplicates
>>>>>>> e53a73a938d60efad84c41173a1037e44240280e
    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX share_agent_unique_institution_organization_names ON share_agent (name) WHERE type in ('share.institution', 'share.organization');",
            reverse_sql="DROP INDEX IF EXISTS share_agent_unique_institution_organization_names;"
        )
    ]
