# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_update_trigger_migrations_20161019_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deliverable',
        ),
        migrations.DeleteModel(
            name='DeliverableVersion',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionVersion',
        ),
        migrations.AlterModelOptions(
            name='abstractcreativeworkversion',
            options={},
        ),
        migrations.AlterModelTable(
            name='abstractagent',
            table='share_agent',
        ),
        migrations.AlterModelTable(
            name='abstractagentrelation',
            table='share_agentrelation',
        ),
        migrations.AlterModelTable(
            name='abstractagentrelationversion',
            table='share_agentrelationversion',
        ),
        migrations.AlterModelTable(
            name='abstractagentversion',
            table='share_agentversion',
        ),
        migrations.AlterModelTable(
            name='abstractagentworkrelation',
            table='share_agentworkrelation',
        ),
        migrations.AlterModelTable(
            name='abstractagentworkrelationversion',
            table='share_agentworkrelationversion',
        ),
        migrations.AlterModelTable(
            name='abstractcreativework',
            table='share_creativework',
        ),
        migrations.AlterModelTable(
            name='abstractcreativeworkversion',
            table='share_creativeworkversion',
        ),
        migrations.AlterModelTable(
            name='abstractworkrelation',
            table='share_workrelation',
        ),
        migrations.AlterModelTable(
            name='abstractworkrelationversion',
            table='share_workrelationversion',
        ),
    ]
