# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.abstractcreativework',),
        ),
        migrations.CreateModel(
            name='RegistrationVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.abstractcreativeworkversion',),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='type',
            field=models.CharField(choices=[('share.creativework', 'creative work'), ('share.preprint', 'preprint'), ('share.manuscript', 'manuscript'), ('share.publication', 'publication'), ('share.project', 'project'), ('share.registration', 'registration')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='type',
            field=models.CharField(choices=[('share.creativeworkversion', 'creative work version'), ('share.preprintversion', 'preprint version'), ('share.manuscriptversion', 'manuscript version'), ('share.publicationversion', 'publication version'), ('share.projectversion', 'project version'), ('share.registrationversion', 'registration version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='type',
            field=models.CharField(choices=[('share.celeryprovidertask', 'celery provider task')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('share.funder', 'funder'), ('share.organization', 'organization'), ('share.publisher', 'publisher'), ('share.institution', 'institution')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='type',
            field=models.CharField(choices=[('share.funderversion', 'funder version'), ('share.organizationversion', 'organization version'), ('share.publisherversion', 'publisher version'), ('share.institutionversion', 'institution version')], db_index=True, max_length=255),
        ),
    ]
