# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 03:11
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import share.models.fields
import share.models.validators
import uuid


class Migration(migrations.Migration):

    replaces = [('share', '0003_triggers'), ('share', '0004_auto_20160708_1630'), ('share', '0005_auto_20160708_1958'), ('share', '0006_auto_20160709_0000'), ('share', '0007_auto_20160709_0135'), ('share', '0008_auto_20160709_0143'), ('share', '0009_auto_20160709_0321'), ('share', '0010_auto_20160709_0554'), ('share', '0011_auto_20160709_0610'), ('share', '0012_auto_20160709_1604'), ('share', '0013_auto_20160709_1714'), ('share', '0014_auto_20160709_1729'), ('share', '0015_auto_20160709_1813'), ('share', '0016_auto_20160709_1917'), ('share', '0017_create_partial_index_on_title'), ('share', '0018_auto_20160710_2132'), ('share', '0019_auto_20160718_1354'), ('share', '0020_update_trigger_migrations_20160718_1354'), ('share', '0021_auto_20160727_1940'), ('share', '0022_auto_20160729_1511'), ('share', '0023_auto_20160809_0132'), ('share', '0024_update_trigger_migrations_20160809_0202'), ('share', '0025_auto_20160812_1512'), ('share', '0026_auto_20160815_1453'), ('share', '0027_auto_20160815_2205')]

    dependencies = [
        ('share', '0002_create_share_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.abstractcreativework',),
        ),
        migrations.CreateModel(
            name='RegistrationVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.abstractcreativeworkversion',),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='type',
            field=models.CharField(choices=[('share.creativework', 'creative work'), ('share.preprint', 'preprint'), ('share.manuscript', 'manuscript'), ('share.publication', 'publication'), ('share.project', 'project'), ('share.registration', 'registration')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='type',
            field=models.CharField(choices=[('share.creativeworkversion', 'creative work version'), ('share.preprintversion', 'preprint version'), ('share.manuscriptversion', 'manuscript version'), ('share.publicationversion', 'publication version'), ('share.projectversion', 'project version'), ('share.registrationversion', 'registration version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='type',
            field=models.CharField(choices=[('share.celeryprovidertask', 'celery provider task')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('share.funder', 'funder'), ('share.organization', 'organization'), ('share.publisher', 'publisher'), ('share.institution', 'institution')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='type',
            field=models.CharField(choices=[('share.funderversion', 'funder version'), ('share.organizationversion', 'organization version'), ('share.publisherversion', 'publisher version'), ('share.institutionversion', 'institution version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='emailversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='emailversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='extra_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterIndexTogether(
            name='change',
            index_together=set([('node_id', 'change_set', 'target_type')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='additional_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='additional_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='family_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='given_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='suffix',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='free_to_read_type',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='free_to_read_type',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='award',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='award',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='community_identifier',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='funder_region',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='isni',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ringgold',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='community_identifier',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='funder_region',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='isni',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='ringgold',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='base_url',
            field=share.models.fields.ShareURLField(),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='url',
            field=share.models.fields.ShareURLField(),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='base_url',
            field=share.models.fields.ShareURLField(),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='url',
            field=share.models.fields.ShareURLField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='gravatar',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='home_page',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='community_identifier',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='community_identifier',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='location',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='venue_type',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=share.models.fields.URIField(),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='url',
            field=share.models.fields.URIField(),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='change',
            name='node_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emailversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.TextField(choices=[('doi', 'DOI'), ('provider', 'Provider'), ('misc', 'Miscellaneous')]),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='type',
            field=models.TextField(choices=[('doi', 'DOI'), ('provider', 'Provider'), ('misc', 'Miscellaneous')]),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='provider_doc_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='sha256',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='first_name',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(64)], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='last_name',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(64)], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='locale',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='long_title',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='robot',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(40)]),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='time_zone',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='username',
            field=models.TextField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', unique=True, validators=[django.core.validators.MaxLengthValidator(64), django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='action',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=share.models.fields.URIField(db_index=True),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='url',
            field=share.models.fields.URIField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='person',
            index_together=set([('family_name', 'given_name', 'additional_name', 'suffix')]),
        ),
        migrations.AlterIndexTogether(
            name='personversion',
            index_together=set([('family_name', 'given_name', 'additional_name', 'suffix')]),
        ),
        migrations.AlterModelOptions(
            name='contributorversion',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='contributor',
            index_together=set([('cited_name', 'order_cited')]),
        ),
        migrations.AlterIndexTogether(
            name='contributorversion',
            index_together=set([('cited_name', 'order_cited')]),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_published',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_published',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='free_to_read_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='free_to_read_type',
            field=share.models.fields.ShareURLField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='language',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='rights',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='free_to_read_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='free_to_read_type',
            field=share.models.fields.ShareURLField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='language',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='rights',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='node_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='additional_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='additional_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='family_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='given_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='suffix',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.RunSQL(
            sql='CREATE INDEX share_abstractcreativework_title_not_too_long ON share_abstractcreativework (title ASC) WHERE octet_length(title) < 2049;',
        ),
        migrations.AlterIndexTogether(
            name='entity',
            index_together=set([('type', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='entityversion',
            index_together=set([('type', 'name')]),
        ),
        migrations.CreateModel(
            name='ThroughAwardEntities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Award')),
                ('award_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AwardVersion')),
                ('change', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardentities', to='share.Change')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Entity')),
                ('entity_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.EntityVersion')),
                ('extra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
                ('same_as', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardEntities')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThroughAwardEntitiesVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Award')),
                ('award_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AwardVersion')),
                ('change', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardentitiesversion', to='share.Change')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Entity')),
                ('entity_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.EntityVersion')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
                ('same_as', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardEntities')),
                ('same_as_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardEntitiesVersion')),
                ('sources', models.ManyToManyField(related_name='source_throughawardentitiesversion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_modified',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='throughawardentities',
            name='same_as_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardEntitiesVersion'),
        ),
        migrations.AddField(
            model_name='throughawardentities',
            name='sources',
            field=models.ManyToManyField(related_name='source_throughawardentities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='throughawardentities',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughawardentities_version', to='share.ThroughAwardEntitiesVersion'),
        ),
        migrations.AddField(
            model_name='award',
            name='entitie_versions',
            field=share.models.fields.TypedManyToManyField(through='share.ThroughAwardEntities', to='share.EntityVersion'),
        ),
        migrations.AddField(
            model_name='award',
            name='entities',
            field=share.models.fields.TypedManyToManyField(through='share.ThroughAwardEntities', to='share.Entity'),
        ),
        migrations.AddField(
            model_name='awardversion',
            name='entitie_versions',
            field=share.models.fields.TypedManyToManyField(through='share.ThroughAwardEntities', to='share.EntityVersion'),
        ),
        migrations.AddField(
            model_name='awardversion',
            name='entities',
            field=share.models.fields.TypedManyToManyField(through='share.ThroughAwardEntities', to='share.Entity'),
        ),
        migrations.AlterModelOptions(
            name='celerytask',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.TextField(choices=[('doi', 'DOI'), ('provider', 'Provider'), ('misc', 'Miscellaneous'), ('eissn', 'Electronic International Standard Serial Number'), ('ark', 'ARK'), ('arxiv', 'arXiv'), ('bibcode', 'bibcode'), ('doi', 'DOI'), ('ean13', 'EAN13'), ('eissn', 'EISSN'), ('handle', 'Handle'), ('isbn', 'ISBN'), ('issn', 'ISSN'), ('istc', 'ISTC'), ('lissn', 'LISSN'), ('lsid', 'LSID'), ('pmid', 'PMID'), ('purl', 'PURL'), ('upc', 'UPC'), ('url', 'URL'), ('urn', 'URN')]),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='type',
            field=models.TextField(choices=[('doi', 'DOI'), ('provider', 'Provider'), ('misc', 'Miscellaneous'), ('eissn', 'Electronic International Standard Serial Number'), ('ark', 'ARK'), ('arxiv', 'arXiv'), ('bibcode', 'bibcode'), ('doi', 'DOI'), ('ean13', 'EAN13'), ('eissn', 'EISSN'), ('handle', 'Handle'), ('isbn', 'ISBN'), ('issn', 'ISSN'), ('istc', 'ISTC'), ('lissn', 'LISSN'), ('lsid', 'LSID'), ('pmid', 'PMID'), ('purl', 'PURL'), ('upc', 'UPC'), ('url', 'URL'), ('urn', 'URN')]),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='app_version',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterModelOptions(
            name='affiliationversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='associationversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='personemailversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='throughawardentitiesversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='throughawardsversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='throughidentifiersversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='throughlinksversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='throughtagsversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='throughvenuesversion',
            options={},
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_abstractcreativework', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_abstractcreativework_version', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_abstractcreativeworkversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_affiliation', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_affiliation_version', to='share.AffiliationVersion'),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_affiliationversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='association',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_association', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='association',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_association_version', to='share.AssociationVersion'),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_associationversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='award',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_award', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='award',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_award_version', to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_awardversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_contributor', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_contributor_version', to='share.ContributorVersion'),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_contributorversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='email',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_email', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='email',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_email_version', to='share.EmailVersion'),
        ),
        migrations.AlterField(
            model_name='emailversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_emailversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_entity', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_entity_version', to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_entityversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_extradata', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_extradata_version', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_extradataversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_identifier', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_identifier_version', to='share.IdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_identifierversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='link',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_link', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='link',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_link_version', to='share.LinkVersion'),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_linkversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='normalizeddata',
            name='normalized_data',
            field=share.models.fields.DateTimeAwareJSONField(default={}, validators=[share.models.validators.JSONLDValidator()]),
        ),
        migrations.AlterField(
            model_name='person',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_person', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='person',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_person_version', to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_personemail', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_personemail_version', to='share.PersonEmailVersion'),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_personemailversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_personversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_tag', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_tag_version', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_tagversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawardentities',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardentities', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawardentities',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughawardentities_version', to='share.ThroughAwardEntitiesVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardentitiesversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardentitiesversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawards', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughawards_version', to='share.ThroughAwardsVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughidentifiers',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughidentifiers', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughidentifiers',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughidentifiers_version', to='share.ThroughIdentifiersVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughidentifiersversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughlinks',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughlinks', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughlinks',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughlinks_version', to='share.ThroughLinksVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughlinksversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughtags', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughtags_version', to='share.ThroughTagsVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughtagsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughvenues', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughvenues_version', to='share.ThroughVenuesVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughvenuesversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_venue', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_venue_version', to='share.VenueVersion'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_venueversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='given_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='family_name',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
