# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20160708_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='additional_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='additional_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='family_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='given_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='suffix',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='name',
            field=models.TextField(),
        ),
    ]
