# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('share', '0005_update_trigger_migrations_20161104_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='model_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='type',
            field=models.CharField(choices=[('share.agent', 'agent'), ('share.organization', 'organization'), ('share.person', 'person'), ('share.consortium', 'consortium'), ('share.institution', 'institution')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='type',
            field=models.CharField(choices=[('share.agentversion', 'agent version'), ('share.organizationversion', 'organization version'), ('share.personversion', 'person version'), ('share.consortiumversion', 'consortium version'), ('share.institutionversion', 'institution version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='type',
            field=models.CharField(choices=[('share.agentworkrelation', 'agent work relation'), ('share.host', 'host'), ('share.funder', 'funder'), ('share.contributor', 'contributor'), ('share.creator', 'creator'), ('share.principalinvestigator', 'principal investigator'), ('share.publisher', 'publisher')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='type',
            field=models.CharField(choices=[('share.agentworkrelationversion', 'agent work relation version'), ('share.hostversion', 'host version'), ('share.funderversion', 'funder version'), ('share.contributorversion', 'contributor version'), ('share.creatorversion', 'creator version'), ('share.principalinvestigatorversion', 'principal investigator version'), ('share.publisherversion', 'publisher version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='type',
            field=models.CharField(choices=[('share.creativework', 'creative work'), ('share.publication', 'publication'), ('share.workingpaper', 'working paper'), ('share.registration', 'registration'), ('share.book', 'book'), ('share.article', 'article'), ('share.report', 'report'), ('share.thesis', 'thesis'), ('share.conferencepaper', 'conference paper'), ('share.project', 'project'), ('share.dissertation', 'dissertation'), ('share.preprint', 'preprint'), ('share.poster', 'poster'), ('share.presentation', 'presentation'), ('share.patent', 'patent'), ('share.software', 'software'), ('share.dataset', 'data set')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='type',
            field=models.CharField(choices=[('share.creativeworkversion', 'creative work version'), ('share.publicationversion', 'publication version'), ('share.workingpaperversion', 'working paper version'), ('share.registrationversion', 'registration version'), ('share.bookversion', 'book version'), ('share.articleversion', 'article version'), ('share.reportversion', 'report version'), ('share.thesisversion', 'thesis version'), ('share.conferencepaperversion', 'conference paper version'), ('share.projectversion', 'project version'), ('share.dissertationversion', 'dissertation version'), ('share.preprintversion', 'preprint version'), ('share.posterversion', 'poster version'), ('share.presentationversion', 'presentation version'), ('share.patentversion', 'patent version'), ('share.softwareversion', 'software version'), ('share.datasetversion', 'data set version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='type',
            field=models.CharField(choices=[('share.workrelation', 'work relation'), ('share.reviews', 'reviews'), ('share.ispartof', 'is part of'), ('share.references', 'references'), ('share.issupplementto', 'is supplement to'), ('share.extends', 'extends'), ('share.isderivedfrom', 'is derived from'), ('share.documents', 'documents'), ('share.compiles', 'compiles'), ('share.isidenticalto', 'is identical to'), ('share.cites', 'cites')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='type',
            field=models.CharField(choices=[('share.workrelationversion', 'work relation version'), ('share.reviewsversion', 'reviews version'), ('share.ispartofversion', 'is part of version'), ('share.referencesversion', 'references version'), ('share.issupplementtoversion', 'is supplement to version'), ('share.extendsversion', 'extends version'), ('share.isderivedfromversion', 'is derived from version'), ('share.documentsversion', 'documents version'), ('share.compilesversion', 'compiles version'), ('share.isidenticaltoversion', 'is identical to version'), ('share.citesversion', 'cites version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relations', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='share.Subject'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.Subject'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='share.Tag'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='scheme',
            field=models.TextField(editable=False, help_text='A prefix to URI indicating how the following data should be interpreted.'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='scheme',
            field=models.TextField(editable=False, help_text='A prefix to URI indicating how the following data should be interpreted.'),
        ),
    ]
