# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_update_trigger_migrations_20161117_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractagent',
            name='name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='change',
            index_together=set([('target_type', 'target_id')]),
        ),
    ]
