# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 01:35
from __future__ import unicode_literals

from django.db import migrations
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20160709_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractcreativework',
            name='free_to_read_type',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='free_to_read_type',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='award',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='award',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='community_identifier',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='funder_region',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='isni',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ringgold',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='community_identifier',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='funder_region',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='isni',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='ringgold',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='base_url',
            field=share.models.fields.ShareURLField(),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='url',
            field=share.models.fields.ShareURLField(),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='base_url',
            field=share.models.fields.ShareURLField(),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='url',
            field=share.models.fields.ShareURLField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='gravatar',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='home_page',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='url',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='community_identifier',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='community_identifier',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='location',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='venue_type',
            field=share.models.fields.ShareURLField(blank=True),
        ),
    ]
