# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_principalinvestigator_principalinvestigatorversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compiles',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='CompilesVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='DocumentsVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='Extends',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='ExtendsVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='IsIdenticalTo',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='IsIdenticalToVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='References',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='ReferencesVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='ReviewsVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
    ]
