# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_compiles_compilesversion_documents_documentsversion_extends_extendsversion_isidenticalto_isidentical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.creativework',),
        ),
        migrations.CreateModel(
            name='PatentVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.creativeworkversion',),
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Determines whether or not this record will be discoverable via search.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='language',
            field=models.TextField(blank=True, help_text='The ISO 3166-1 alpha-2 country code indicating the language of this record.', null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Determines whether or not this record will be discoverable via search.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='language',
            field=models.TextField(blank=True, help_text='The ISO 3166-1 alpha-2 country code indicating the language of this record.', null=True),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='agentidentifier',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='agentidentifier',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='agentidentifierversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='agentidentifierversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
    ]
