# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_auto_20161122_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrects',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='CorrectsVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='Discusses',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='DiscussesVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='Disputes',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='DisputesVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='RepliesTo',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='RepliesToVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='Retraction',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.abstractcreativework',),
        ),
        migrations.CreateModel(
            name='RetractionVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.abstractcreativeworkversion',),
        ),
        migrations.CreateModel(
            name='Retracts',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='RetractsVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_agent_relations', to='share.AbstractAgent'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_agent_relations', to='share.AbstractAgent'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterIndexTogether(
            name='change',
            index_together=set([]),
        ),
    ]
