# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_auto_20161122_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryDisambiguatorTask',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.celerytask',),
        ),
        migrations.AddField(
            model_name='celerytask',
            name='id_started_by',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='celerytask',
            name='normalized_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='type',
            field=models.CharField(choices=[('share.celerydisambiguatortask', 'celery disambiguator task'), ('share.celeryprovidertask', 'celery provider task')], db_index=True, max_length=255),
        ),
        migrations.AlterIndexTogether(
            name='change',
            index_together=set([]),
        ),
    ]
