# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_auto_20161122_1810'),
    ]

    operations = [
        migrations.RenameModel('CeleryProviderTask', 'CeleryAppTask'),
        migrations.RenameField('CeleryTask', 'provider', 'source'),
        migrations.AlterField(
            model_name='celerytask',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='type',
            field=models.CharField(choices=[('share.celeryapptask', 'celery app task')], db_index=True, max_length=255),
        ),
    ]
