# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_auto_20161122_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractagentworkrelation',
            name='contributed_throug_versions',
        ),
        migrations.RemoveField(
            model_name='abstractagentworkrelationversion',
            name='contributed_throug_versions',
        ),
        migrations.AddField(
            model_name='abstractagentworkrelation',
            name='contributed_through_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, related_name='_abstractagentworkrelation_contributed_through_versions_+', through='share.ThroughContributor', to='share.AbstractAgentWorkRelationVersion'),
        ,
        migrations.AddField(
            model_name='abstractagentworkrelationversion',
            name='contributed_through_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, related_name='_abstractagentworkrelationversion_contributed_through_versions_+', through='share.ThroughContributor', to='share.AbstractAgentWorkRelationVersion'),
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_agent_relations', to='share.AbstractAgent'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_agent_relations', to='share.AbstractAgent'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='agentidentifier',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='award',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='subject',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.Subject'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterIndexTogether(
            name='change',
            index_together=set([]),
        ),
    ]
