# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_compiles_compilesversion_documents_documentsversion_extends_extendsversion_isidenticalto_isidentical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='lineages',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='parents',
        ),
        migrations.AddField(
            model_name='subject',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.Subject'),
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='type',
            field=models.CharField(choices=[('share.agent', 'agent'), ('share.organization', 'organization'), ('share.institution', 'institution'), ('share.person', 'person'), ('share.consortium', 'consortium')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='type',
            field=models.CharField(choices=[('share.agentrelation', 'agent relation'), ('share.isaffiliatedwith', 'is affiliated with'), ('share.ismemberof', 'is member of'), ('share.isemployedby', 'is employed by')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='type',
            field=models.CharField(choices=[('share.agentrelationversion', 'agent relation version'), ('share.isaffiliatedwithversion', 'is affiliated with version'), ('share.ismemberofversion', 'is member of version'), ('share.isemployedbyversion', 'is employed by version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='type',
            field=models.CharField(choices=[('share.agentversion', 'agent version'), ('share.organizationversion', 'organization version'), ('share.institutionversion', 'institution version'), ('share.personversion', 'person version'), ('share.consortiumversion', 'consortium version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='type',
            field=models.CharField(choices=[('share.agentworkrelation', 'agent work relation'), ('share.funder', 'funder'), ('share.publisher', 'publisher'), ('share.contributor', 'contributor'), ('share.principalinvestigator', 'principal investigator'), ('share.creator', 'creator'), ('share.host', 'host')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='type',
            field=models.CharField(choices=[('share.agentworkrelationversion', 'agent work relation version'), ('share.funderversion', 'funder version'), ('share.publisherversion', 'publisher version'), ('share.contributorversion', 'contributor version'), ('share.principalinvestigatorversion', 'principal investigator version'), ('share.creatorversion', 'creator version'), ('share.hostversion', 'host version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Determines whether or not this record will be discoverable via search.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='language',
            field=models.TextField(blank=True, help_text='The ISO 3166-1 alpha-2 country code indicating the language of this record.', null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='type',
            field=models.CharField(choices=[('share.creativework', 'creative work'), ('share.poster', 'poster'), ('share.presentation', 'presentation'), ('share.software', 'software'), ('share.dataset', 'data set'), ('share.publication', 'publication'), ('share.thesis', 'thesis'), ('share.book', 'book'), ('share.registration', 'registration'), ('share.project', 'project'), ('share.preprint', 'preprint'), ('share.article', 'article'), ('share.dissertation', 'dissertation'), ('share.workingpaper', 'working paper'), ('share.report', 'report'), ('share.conferencepaper', 'conference paper')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Determines whether or not this record will be discoverable via search.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='language',
            field=models.TextField(blank=True, help_text='The ISO 3166-1 alpha-2 country code indicating the language of this record.', null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='type',
            field=models.CharField(choices=[('share.creativeworkversion', 'creative work version'), ('share.posterversion', 'poster version'), ('share.presentationversion', 'presentation version'), ('share.softwareversion', 'software version'), ('share.datasetversion', 'data set version'), ('share.publicationversion', 'publication version'), ('share.thesisversion', 'thesis version'), ('share.bookversion', 'book version'), ('share.registrationversion', 'registration version'), ('share.projectversion', 'project version'), ('share.preprintversion', 'preprint version'), ('share.articleversion', 'article version'), ('share.dissertationversion', 'dissertation version'), ('share.workingpaperversion', 'working paper version'), ('share.reportversion', 'report version'), ('share.conferencepaperversion', 'conference paper version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='type',
            field=models.CharField(choices=[('share.workrelation', 'work relation'), ('share.cites', 'cites'), ('share.references', 'references'), ('share.isderivedfrom', 'is derived from'), ('share.isidenticalto', 'is identical to'), ('share.issupplementto', 'is supplement to'), ('share.compiles', 'compiles'), ('share.reviews', 'reviews'), ('share.extends', 'extends'), ('share.ispartof', 'is part of'), ('share.documents', 'documents')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='type',
            field=models.CharField(choices=[('share.workrelationversion', 'work relation version'), ('share.citesversion', 'cites version'), ('share.referencesversion', 'references version'), ('share.isderivedfromversion', 'is derived from version'), ('share.isidenticaltoversion', 'is identical to version'), ('share.issupplementtoversion', 'is supplement to version'), ('share.compilesversion', 'compiles version'), ('share.reviewsversion', 'reviews version'), ('share.extendsversion', 'extends version'), ('share.ispartofversion', 'is part of version'), ('share.documentsversion', 'documents version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agentidentifier',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='agentidentifier',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='agentidentifierversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='agentidentifierversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='type',
            field=models.CharField(choices=[('share.celeryprovidertask', 'celery provider task')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date this record was modified by SHARE.'),
        ),
    ]
