# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_auto_20161207_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsIdenticalTo',
        ),
        migrations.DeleteModel(
            name='IsIdenticalToVersion',
        ),
        migrations.CreateModel(
            name='Corrects',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='CorrectsVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='Discusses',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='DiscussesVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='Disputes',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='DisputesVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='RepliesTo',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='RepliesToVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.CreateModel(
            name='Retraction',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.creativework',),
        ),
        migrations.CreateModel(
            name='RetractionVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.creativeworkversion',),
        ),
        migrations.CreateModel(
            name='Retracts',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='RetractsVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
    ]
