# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 14:18
from __future__ import unicode_literals

import db.deletion
from django.conf import settings
from django.db import migrations, models
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_auto_20161212_1418_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workidentifierversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.WorkIdentifier'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentRelation'),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgent'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelation'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractWorkRelation'),
        ),
        migrations.AlterField(
            model_name='agentidentifierversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AgentIdentifier'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.Award'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.Tag'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughAwards'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughContributor'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughSubjects'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughTags'),
        ),
    ]
