# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 14:18
from __future__ import unicode_literals

import db.deletion
from django.conf import settings
from django.db import migrations, models
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_auto_20161212_1418_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sources',
            field=share.models.fields.TypedManyToManyField(editable=False, related_name='source_tag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_tag_version', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_tagversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='extra_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.Tag'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='award',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.Award'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='award_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughawards', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='funder',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.AbstractAgentWorkRelation'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='funder_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelationVersion'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughAwards'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughAwardsVersion'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='sources',
            field=share.models.fields.TypedManyToManyField(editable=False, related_name='source_throughawards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_throughawards_version', to='share.ThroughAwardsVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='award',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.Award'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='award_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughawardsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='extra_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='funder',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelation'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='funder_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelationVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughAwards'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughAwardsVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughcontributor', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='related',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelation'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='related_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelationVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughContributor'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughContributorVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='sources',
            field=share.models.fields.TypedManyToManyField(editable=False, related_name='source_throughcontributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='subject',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelation'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='subject_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelationVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_throughcontributor_version', to='share.ThroughContributorVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughcontributorversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='extra_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='related',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelation'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='related_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelationVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughContributor'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughContributorVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='subject',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelation'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='subject_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractAgentWorkRelationVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughsubjects', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='creative_work',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='subject_relations', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='creative_work_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughSubjects'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughSubjectsVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='sources',
            field=share.models.fields.TypedManyToManyField(editable=False, related_name='source_throughsubjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_throughsubjects_version', to='share.ThroughSubjectsVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughsubjectsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='creative_work',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='creative_work_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='extra_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughSubjects'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughSubjectsVersion'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughtags', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='creative_work',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='tag_relations', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='creative_work_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughTags'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughTagsVersion'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='sources',
            field=share.models.fields.TypedManyToManyField(editable=False, related_name='source_throughtags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='tag',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='work_relations', to='share.Tag'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='tag_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_throughtags_version', to='share.ThroughTagsVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughtagsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='creative_work',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='creative_work_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='extra_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughTags'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ThroughTagsVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='tag',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.Tag'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='tag_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_workidentifier', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='creative_work',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='identifiers', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='creative_work_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='extra_version',
            field=models.OneToOneField(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.WorkIdentifier'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.WorkIdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='sources',
            field=share.models.fields.TypedManyToManyField(editable=False, related_name='source_workidentifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_workidentifier_version', to='share.WorkIdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_workidentifierversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='creative_work',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='creative_work_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='extra_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.WorkIdentifier'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='same_as_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.WorkIdentifierVersion'),
        ),
    ]
