# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 05:54
from __future__ import unicode_literals

from django.db import migrations
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_auto_20160709_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=share.models.fields.URIField(db_index=True),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='url',
            field=share.models.fields.URIField(db_index=True),
        ),
    ]
