# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_auto_20160709_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='person',
            index_together=set([('family_name', 'given_name', 'additional_name', 'suffix')]),
        ),
        migrations.AlterIndexTogether(
            name='personversion',
            index_together=set([('family_name', 'given_name', 'additional_name', 'suffix')]),
        ),
    ]
