# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0011_auto_20160709_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributorversion',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='contributor',
            index_together=set([('cited_name', 'order_cited')]),
        ),
        migrations.AlterIndexTogether(
            name='contributorversion',
            index_together=set([('cited_name', 'order_cited')]),
        ),
    ]
