# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_auto_20160709_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_published',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_published',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
