# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_auto_20161212_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.organization',),
        ),
        migrations.CreateModel(
            name='DepartmentVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.organizationversion',),
        ),
        migrations.CreateModel(
            name='PrincipalInvestigatorContact',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.principalinvestigator',),
        ),
        migrations.CreateModel(
            name='PrincipalInvestigatorContactVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.principalinvestigatorversion',),
        ),
        migrations.AddField(
            model_name='award',
            name='award_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awardversion',
            name='award_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awardversion',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='type',
            field=models.CharField(choices=[('share.agent', 'agent'), ('share.organization', 'organization'), ('share.consortium', 'consortium'), ('share.department', 'department'), ('share.institution', 'institution'), ('share.person', 'person')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='type',
            field=models.CharField(choices=[('share.agentversion', 'agent version'), ('share.organizationversion', 'organization version'), ('share.consortiumversion', 'consortium version'), ('share.departmentversion', 'department version'), ('share.institutionversion', 'institution version'), ('share.personversion', 'person version')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='type',
            field=models.CharField(choices=[('share.agentworkrelation', 'agent work relation'), ('share.contributor', 'contributor'), ('share.creator', 'creator'), ('share.principalinvestigator', 'principal investigator'), ('share.principalinvestigatorcontact', 'principal investigator contact'), ('share.funder', 'funder'), ('share.host', 'host'), ('share.publisher', 'publisher')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='type',
            field=models.CharField(choices=[('share.agentworkrelationversion', 'agent work relation version'), ('share.contributorversion', 'contributor version'), ('share.creatorversion', 'creator version'), ('share.principalinvestigatorversion', 'principal investigator version'), ('share.principalinvestigatorcontactversion', 'principal investigator contact version'), ('share.funderversion', 'funder version'), ('share.hostversion', 'host version'), ('share.publisherversion', 'publisher version')], db_index=True, max_length=255),
        ),
    ]
