# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_auto_20160709_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractcreativeworkversion',
            options={},
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_published',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='language',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='rights',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_published',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='language',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='rights',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='abstractcreativework',
            index_together=set([('type', 'date_updated', 'rights', 'language', 'title')]),
        ),
        migrations.AlterIndexTogether(
            name='abstractcreativeworkversion',
            index_together=set([('type', 'date_updated', 'rights', 'language', 'title')]),
        ),
    ]
