# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_auto_20160709_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractcreativeworkversion',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='abstractcreativework',
            index_together=set([('type', 'date_updated', 'rights', 'title')]),
        ),
        migrations.AlterIndexTogether(
            name='abstractcreativeworkversion',
            index_together=set([('type', 'date_updated', 'rights', 'title')]),
        ),
    ]
