# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_auto_20160709_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractcreativework',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='title',
            field=models.TextField(db_index=True),
        ),
    ]
