# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0013_auto_20161214_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizeddata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
