# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0013_auto_20160709_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractcreativework',
            name='free_to_read_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='free_to_read_type',
            field=share.models.fields.ShareURLField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='language',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='rights',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='free_to_read_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='free_to_read_type',
            field=share.models.fields.ShareURLField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='language',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='rights',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
