# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 20:23
from __future__ import unicode_literals

import db.deletion
from django.conf import settings
from django.db import migrations, models
import share.models.core


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0014_auto_20170112_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaviconImage',
            fields=[
                ('user', models.OneToOneField(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='shareuser',
            name='favicon',
            field=models.ImageField(blank=True, storage=share.models.core.FaviconStorage(), upload_to=share.models.core.favicon_name),
        ),
    ]
