# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0015_auto_20160709_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='additional_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='additional_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='family_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='given_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='suffix',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
