# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 21:30
from __future__ import unicode_literals

from django.db import migrations
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0015_auto_20170117_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='uri',
            field=share.models.fields.ShareURLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='uri',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
    ]
