# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0015_auto_20170117_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='uri',
            field=share.models.fields.ShareURLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='uri',
            field=share.models.fields.ShareURLField(blank=True),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.creativework',),
        ),
        migrations.CreateModel(
            name='RepositoryVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.creativeworkversion',),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='type',
            field=models.CharField(choices=[('share.creativework', 'creative work'), ('share.dataset', 'data set'), ('share.patent', 'patent'), ('share.poster', 'poster'), ('share.presentation', 'presentation'), ('share.publication', 'publication'), ('share.article', 'article'), ('share.book', 'book'), ('share.conferencepaper', 'conference paper'), ('share.dissertation', 'dissertation'), ('share.preprint', 'preprint'), ('share.project', 'project'), ('share.registration', 'registration'), ('share.report', 'report'), ('share.thesis', 'thesis'), ('share.workingpaper', 'working paper'), ('share.repository', 'repository'), ('share.retraction', 'retraction'), ('share.software', 'software')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='type',
            field=models.CharField(choices=[('share.creativeworkversion', 'creative work version'), ('share.datasetversion', 'data set version'), ('share.patentversion', 'patent version'), ('share.posterversion', 'poster version'), ('share.presentationversion', 'presentation version'), ('share.publicationversion', 'publication version'), ('share.articleversion', 'article version'), ('share.bookversion', 'book version'), ('share.conferencepaperversion', 'conference paper version'), ('share.dissertationversion', 'dissertation version'), ('share.preprintversion', 'preprint version'), ('share.projectversion', 'project version'), ('share.registrationversion', 'registration version'), ('share.reportversion', 'report version'), ('share.thesisversion', 'thesis version'), ('share.workingpaperversion', 'working paper version'), ('share.repositoryversion', 'repository version'), ('share.retractionversion', 'retraction version'), ('share.softwareversion', 'software version')], db_index=True, max_length=255),
        ),
    ]
