# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0014_auto_20170127_1423'),
        ('share', '0015_auto_20170117_2050'),
    ]

    operations = [
    ]
