# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0016_auto_20160709_1917'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX share_abstractcreativework_title_not_too_long ON share_abstractcreativework (title ASC) WHERE octet_length(title) < 1025;"
        )
    ]
