# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0014_auto_20170112_2143'),
        ('share', '0016_merge'),
        ('share', '0016_auto_20170130_2130'),
    ]

    operations = [
    ]
