# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0017_create_partial_index_on_title'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='entity',
            index_together=set([('type', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='entityversion',
            index_together=set([('type', 'name')]),
        ),
    ]
