# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 16:18
from __future__ import unicode_literals

import db.deletion
from django.conf import settings
from django.db import migrations, models
import share.models.core


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0017_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaviconImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='shareuser',
            name='favicon',
            field=models.ImageField(null=True, storage=share.models.source.SourceIconStorage(), upload_to=share.models.source.icon_name),
        ),
        migrations.AddField(
            model_name='faviconimage',
            name='user',
            field=models.OneToOneField(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to=settings.AUTH_USER_MODEL),
        ),
    ]
