# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0017_merge'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE OR REPLACE FUNCTION count_estimate(query text) RETURNS INTEGER AS
                $func$
                DECLARE
                    rec   record;
                    ROWS  INTEGER;
                BEGIN
                    FOR rec IN EXECUTE 'EXPLAIN ' || query LOOP
                        ROWS := SUBSTRING(rec."QUERY PLAN" FROM ' rows=([[:digit:]]+)');
                        EXIT WHEN ROWS IS NOT NULL;
                    END LOOP;

                    RETURN ROWS - 1;
                END
                $func$ LANGUAGE plpgsql;
            ''',
            reverse_sql='DROP FUNCTION count_estimate();',
        ),
    ]
