# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0018_fuzzycount'),
        ('share', '0018_store_favicons'),
    ]

    operations = [
    ]
