# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import share.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0018_auto_20160710_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThroughAwardFunders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Award')),
                ('award_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AwardVersion')),
                ('change', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardfunders', to='share.Change')),
                ('extra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Funder')),
                ('funder_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.FunderVersion')),
                ('same_as', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardFunders')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThroughAwardFundersVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Award')),
                ('award_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AwardVersion')),
                ('change', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardfundersversion', to='share.Change')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Funder')),
                ('funder_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.FunderVersion')),
                ('same_as', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardFunders')),
                ('same_as_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardFundersVersion')),
                ('sources', models.ManyToManyField(related_name='source_throughawardfundersversion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ('-date_modified',),
            },
        ),
        migrations.AddField(
            model_name='throughawardfunders',
            name='same_as_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardFundersVersion'),
        ),
        migrations.AddField(
            model_name='throughawardfunders',
            name='sources',
            field=models.ManyToManyField(related_name='source_throughawardfunders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='throughawardfunders',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughawardfunders_version', to='share.ThroughAwardFundersVersion'),
        ),
        migrations.AddField(
            model_name='award',
            name='funde_versions',
            field=share.models.fields.TypedManyToManyField(through='share.ThroughAwardFunders', to='share.FunderVersion'),
        ),
        migrations.AddField(
            model_name='award',
            name='funder',
            field=share.models.fields.TypedManyToManyField(through='share.ThroughAwardFunders', to='share.Funder'),
        ),
        migrations.AddField(
            model_name='awardversion',
            name='funde_versions',
            field=share.models.fields.TypedManyToManyField(through='share.ThroughAwardFunders', to='share.FunderVersion'),
        ),
        migrations.AddField(
            model_name='awardversion',
            name='funder',
            field=share.models.fields.TypedManyToManyField(through='share.ThroughAwardFunders', to='share.Funder'),
        ),
    ]
