# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0020_update_trigger_migrations_20160718_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celerytask',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.TextField(choices=[('doi', 'DOI'), ('provider', 'Provider'), ('misc', 'Miscellaneous'), ('eissn', 'Electronic International Standard Serial Number'), ('ark', 'ARK'), ('arxiv', 'arXiv'), ('bibcode', 'bibcode'), ('doi', 'DOI'), ('ean13', 'EAN13'), ('eissn', 'EISSN'), ('handle', 'Handle'), ('isbn', 'ISBN'), ('issn', 'ISSN'), ('istc', 'ISTC'), ('lissn', 'LISSN'), ('lsid', 'LSID'), ('pmid', 'PMID'), ('purl', 'PURL'), ('upc', 'UPC'), ('url', 'URL'), ('urn', 'URN')]),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='type',
            field=models.TextField(choices=[('doi', 'DOI'), ('provider', 'Provider'), ('misc', 'Miscellaneous'), ('eissn', 'Electronic International Standard Serial Number'), ('ark', 'ARK'), ('arxiv', 'arXiv'), ('bibcode', 'bibcode'), ('doi', 'DOI'), ('ean13', 'EAN13'), ('eissn', 'EISSN'), ('handle', 'Handle'), ('isbn', 'ISBN'), ('issn', 'ISSN'), ('istc', 'ISTC'), ('lissn', 'LISSN'), ('lsid', 'LSID'), ('pmid', 'PMID'), ('purl', 'PURL'), ('upc', 'UPC'), ('url', 'URL'), ('urn', 'URN')]),
        ),
    ]
