# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0020_auto_20170206_2114'),
    ]

    # Add 'same_as_id IS NOT NULL' condition
    operations = [
        migrations.RunSQL([
            'DROP INDEX IF EXISTS share_agent_unique_institution_organization_names;',
            "CREATE UNIQUE INDEX share_agent_unique_institution_organization_names ON share_agent (name) WHERE type in ('share.institution', 'share.organization', 'share.consortium') AND same_as_id IS NOT NULL;",
        ])
    ]
