# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0021_auto_20160727_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='app_version',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
