# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0022_system_superuser'),
    ]

    operations = [
        migrations.RunSQL('''
            SELECT
                rawdata.provider_doc_id AS identifier
                , source_config.id AS source_config_id
            INTO
                share_sourceuniqueidentifier
            FROM
                share_rawdata AS rawdata
            JOIN
                share_sourceconfig AS source_config ON rawdata.app_label = sourceconfig.label
            ;
        '''),
        migrations.RunSQL('''
            UPDATE
                share_rawdata AS rawdata
            SET
                rawdata.suid_id = (
                    SELECT
                        id
                    FROM
                        share_sourceuniqueidentifier AS sourceuniqueidentifier
                    JOIN
                        share_sourceconfig AS sourceconfig ON sourceuniqueidentifier.source_config_id = sourceconfig.id
                    WHERE
                        sourceuniqueidentifier.identifier = rawdata.provider_doc_id
                    AND
                        sourceconfig.label = rawdata.app_label
                    LIMIT 1
                )
            WHERE
                rawdata.suid_id IS NULL
            ;
        '''),
    ]
