# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0023_auto_20170224_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='suid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier'),
            preserve_default=False,
        ),
    ]
