# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0023_auto_20170221_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconfig',
            name='version',
            field=models.TextField(default='000.000.000'),
        ),
    ]
