# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import share.models.core


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0023_rawdatatodatum'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Enqueued'), (1, 'In Progress'), (2, 'Failed'), (2, 'Succeeded'), (2, 'Rescheduled')], db_index=True, default=0)),
                ('error', models.TextField(blank=True)),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('share_version', models.TextField(default='2.4.0-8-g0017cdd')),
                ('harvester_version', models.TextField()),
                ('source_config_version', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SourceUniqueIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('source_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceConfig')),
            ],
        ),
        migrations.AlterModelOptions(
            name='rawdatum',
            options={'verbose_name_plural': 'Raw Data'},
        ),
        migrations.AlterField(
            model_name='rawdatum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shareuser',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=share.models.core.FaviconStorage(), upload_to=share.models.core.favicon_name),
        ),
        migrations.RemoveField(
            model_name='rawdatum',
            name='app_label',
        ),
        migrations.RemoveField(
            model_name='rawdatum',
            name='date_harvested',
        ),
        migrations.RemoveField(
            model_name='rawdatum',
            name='date_seen',
        ),
        migrations.RemoveField(
            model_name='rawdatum',
            name='provider_doc_id',
        ),
        migrations.RemoveField(
            model_name='rawdatum',
            name='source',
        ),
        migrations.RemoveField(
            model_name='rawdatum',
            name='tasks',
        ),
        migrations.AddField(
            model_name='rawdatum',
            name='logs',
            field=models.ManyToManyField(to='share.HarvestLog'),
        ),
        migrations.AlterUniqueTogether(
            name='rawdatum',
            unique_together=set([('suid', 'sha256')]),
        ),
        migrations.AddField(
            model_name='harvestlog',
            name='source_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceConfig'),
        ),
        migrations.AddField(
            model_name='rawdatum',
            name='suid',
            field=models.ForeignKey(default='fake', on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sourceuniqueidentifier',
            unique_together=set([('identifier', 'source_config')]),
        ),
        migrations.AlterUniqueTogether(
            name='harvestlog',
            unique_together=set([('source_config', 'start_date', 'end_date', 'harvester_version', 'source_config_version')]),
        ),
    ]
