# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import share.models.fields
import share.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0024_update_trigger_migrations_20160809_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractcreativework',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_abstractcreativework', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_abstractcreativework_version', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_abstractcreativeworkversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_affiliation', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_affiliation_version', to='share.AffiliationVersion'),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_affiliationversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='association',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_association', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='association',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_association_version', to='share.AssociationVersion'),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_associationversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='award',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_award', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='award',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_award_version', to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_awardversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_contributor', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_contributor_version', to='share.ContributorVersion'),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_contributorversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='email',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_email', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='email',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_email_version', to='share.EmailVersion'),
        ),
        migrations.AlterField(
            model_name='emailversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_emailversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_entity', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_entity_version', to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_entityversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_extradata', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_extradata_version', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_extradataversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_identifier', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_identifier_version', to='share.IdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_identifierversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='link',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_link', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='link',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_link_version', to='share.LinkVersion'),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_linkversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='normalizeddata',
            name='normalized_data',
            field=share.models.fields.DatetimeAwareJSONField(default={}, validators=[share.models.validators.JSONLDValidator()]),
        ),
        migrations.AlterField(
            model_name='person',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_person', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='person',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_person_version', to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_personemail', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_personemail_version', to='share.PersonEmailVersion'),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_personemailversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_personversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_tag', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_tag_version', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_tagversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawardentities',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardentities', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawardentities',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughawardentities_version', to='share.ThroughAwardEntitiesVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardentitiesversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardentitiesversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawards', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughawards_version', to='share.ThroughAwardsVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughidentifiers',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughidentifiers', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughidentifiers',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughidentifiers_version', to='share.ThroughIdentifiersVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughidentifiersversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughlinks',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughlinks', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughlinks',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughlinks_version', to='share.ThroughLinksVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughlinksversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughtags', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughtags_version', to='share.ThroughTagsVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughtagsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughvenues', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughvenues_version', to='share.ThroughVenuesVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughvenuesversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_venue', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_venue_version', to='share.VenueVersion'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_venueversion', to='share.Change'),
        ),
    ]
