# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 19:30
from __future__ import unicode_literals

import db.deletion
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0025_sources_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaviconImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('user', models.OneToOneField(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Enqueued'), (1, 'In Progress'), (2, 'Failed'), (3, 'Succeeded'), (4, 'Rescheduled'), (5, 'Defunct'), (5, 'Forced')], db_index=True, default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('completions', models.IntegerField(default=0)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('share_version', models.TextField(default='2.4.2-39-gd06fc6e1', validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\.\\d\\d\\d\\.\\d\\d\\d$')])),
                ('source_config_version', models.PositiveIntegerField()),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('harvester_version', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IngestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Enqueued'), (1, 'In Progress'), (2, 'Failed'), (3, 'Succeeded'), (4, 'Rescheduled'), (5, 'Defunct'), (5, 'Forced')], db_index=True, default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('completions', models.IntegerField(default=0)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('share_version', models.TextField(default='2.4.2-39-gd06fc6e1', validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\.\\d\\d\\d\\.\\d\\d\\d$')])),
                ('source_config_version', models.PositiveIntegerField()),
                ('regulator_version', models.TextField(blank=True, default='', validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\.\\d\\d\\d\\.\\d\\d\\d$')])),
                ('transformer_version', models.TextField(validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\.\\d\\d\\d\\.\\d\\d\\d$')])),
                ('consolidator_version', models.TextField(blank=True, default='', validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\.\\d\\d\\d\\.\\d\\d\\d$')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='rawdatum',
            options={'verbose_name_plural': 'Raw Data'},
        ),
        migrations.RemoveField(
            model_name='rawdatum',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='rawdatum',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='rawdatum',
            name='tasks',
        ),
        migrations.AddField(
            model_name='rawdatum',
            name='created',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourceconfig',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rawdatum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ingestlog',
            name='raw_datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.RawDatum'),
        ),
        migrations.AddField(
            model_name='ingestlog',
            name='source_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceConfig'),
        ),
        migrations.AddField(
            model_name='harvestlog',
            name='source_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceConfig'),
        ),
        migrations.AddField(
            model_name='rawdatum',
            name='logs',
            field=models.ManyToManyField(related_name='raw_data', to='share.HarvestLog'),
        ),
        migrations.AlterUniqueTogether(
            name='ingestlog',
            unique_together=set([('raw_datum', 'transformer_version')]),
        ),
        migrations.AlterUniqueTogether(
            name='harvestlog',
            unique_together=set([('source_config', 'start_date', 'end_date', 'harvester_version', 'source_config_version')]),
        ),
    ]
