# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 17:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0025_auto_20170315_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceconfig',
            name='earliest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourceconfig',
            name='harvester_kwargs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourceconfig',
            name='transformer_kwargs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
