# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0025_auto_20160812_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractcreativework',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='given_name',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
