# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0025_harvestlog_completions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatum',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='harvestlog',
            name='share_version',
            field=models.TextField(default='2.4.0-33-gc304c57'),
        ),
    ]
