# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0026_auto_20170221_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestlog',
            name='raw_data',
            field=models.ManyToManyField(to='share.RawDatum'),
        ),
    ]
