# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0026_auto_20160815_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='family_name',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
