# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0026_auto_20170324_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestlog',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='harvestlog',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='harvestlog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Enqueued'), (1, 'In Progress'), (2, 'Failed'), (3, 'Succeeded'), (4, 'Rescheduled'), (6, 'Forced'), (7, 'Skipped'), (8, 'Retrying')], db_index=True, default=0),
        ),
    ]
