# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import share.models.ingest


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0027_harvestlog_datetime_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='icon',
            field=models.ImageField(blank=True, default='', storage=share.models.ingest.SourceIconStorage(), upload_to=share.models.ingest.icon_name),
            preserve_default=False,
        ),
    ]
