# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 02:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import share.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0027_auto_20160815_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineages', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('parents', models.ManyToManyField(related_name='_subject_parents_+', to='share.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.TextField(db_index=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='share.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughSubjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughsubjects', to='share.Change')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughSubjectsVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughsubjectsversion', to='share.Change')),
            ],
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='subject_version',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='subject_version',
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='award_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughAwards', to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_abstractcreativework', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='contributor_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Contributor', to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='funder_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Association', to='share.FunderVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='institution_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Association', to='share.InstitutionVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='link_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughLinks', to='share.LinkVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='organization_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Association', to='share.OrganizationVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='publisher_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Association', to='share.PublisherVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_abstractcreativework', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='tag_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, related_name='tagged_abstractcreativework', through='share.ThroughTags', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='venue_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughVenues', to='share.VenueVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='award_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughAwards', to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_abstractcreativeworkversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='contributor_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Contributor', to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='funder_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Association', to='share.FunderVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='institution_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Association', to='share.InstitutionVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='link_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughLinks', to='share.LinkVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='organization_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Association', to='share.OrganizationVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='publisher_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Association', to='share.PublisherVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_abstractcreativeworkversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='tag_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, related_name='tagged_abstractcreativeworkversion', through='share.ThroughTags', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='venue_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughVenues', to='share.VenueVersion'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_affiliation', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='entity_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='person_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AffiliationVersion'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_affiliation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_affiliationversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='entity_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='person_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AffiliationVersion'),
        ),
        migrations.AlterField(
            model_name='affiliationversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_affiliationversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='association',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_association', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='association',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='association',
            name='entity_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='association',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='association',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AssociationVersion'),
        ),
        migrations.AlterField(
            model_name='association',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_association', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_associationversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='entity_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AssociationVersion'),
        ),
        migrations.AlterField(
            model_name='associationversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_associationversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='award',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_award', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='award',
            name='entitie_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughAwardEntities', to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='award',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='award',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='award',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_award', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_awardversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='entitie_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughAwardEntities', to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_awardversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_contributor', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='person_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ContributorVersion'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_contributorversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='person_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ContributorVersion'),
        ),
        migrations.AlterField(
            model_name='contributorversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_contributorversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_email', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='email',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='email',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EmailVersion'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_emailversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='emailversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='emailversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EmailVersion'),
        ),
        migrations.AlterField(
            model_name='emailversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_emailversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entity',
            name='affiliation_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Affiliation', to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_entity', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_entity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='affiliation_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Affiliation', to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_entityversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_entityversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_extradata', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_extradata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_extradataversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_extradataversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_identifier', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.IdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_identifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_identifierversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.IdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='identifierversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_identifierversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_link', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='link',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='link',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.LinkVersion'),
        ),
        migrations.AlterField(
            model_name='link',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_linkversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.LinkVersion'),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_linkversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='affiliation_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Affiliation', to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='person',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_person', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.PersonEmail', to='share.EmailVersion'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='person',
            name='identifier_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughIdentifiers', to='share.IdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='person',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_personemail', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='email_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.EmailVersion'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='person_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.PersonEmailVersion'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_personemail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_personemailversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='email_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.EmailVersion'),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='person_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.PersonEmailVersion'),
        ),
        migrations.AlterField(
            model_name='personemailversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_personemailversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='affiliation_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Affiliation', to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_personversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='email_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.PersonEmail', to='share.EmailVersion'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='identifier_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughIdentifiers', to='share.IdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_personversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_tag', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_tag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_tagversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_tagversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughawardentities',
            name='award_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardentities',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardentities', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawardentities',
            name='entity_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardentities',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardentities',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardEntitiesVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardentities',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughawardentities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughawardentitiesversion',
            name='award_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardentitiesversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardentitiesversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawardentitiesversion',
            name='entity_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.EntityVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardentitiesversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardentitiesversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardEntitiesVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardentitiesversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughawardentitiesversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='award_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawards', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardsVersion'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughawards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='award_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughawardsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughAwardsVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughawardsversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughidentifiers',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughidentifiers', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughidentifiers',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiers',
            name='identifier_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.IdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiers',
            name='person_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiers',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughIdentifiersVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiers',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughidentifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughidentifiersversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='identifier_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.IdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='person_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.PersonVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughIdentifiersVersion'),
        ),
        migrations.AlterField(
            model_name='throughidentifiersversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughidentifiersversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughlinks',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughlinks', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughlinks',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinks',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinks',
            name='link_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.LinkVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinks',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughLinksVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinks',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughlinks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughlinksversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='link_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.LinkVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughLinksVersion'),
        ),
        migrations.AlterField(
            model_name='throughlinksversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughlinksversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughtags', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughTagsVersion'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughtags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='tag_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughtagsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughTagsVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughtagsversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='tag_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughvenues', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughVenuesVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughvenues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughvenues',
            name='venue_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.VenueVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughvenuesversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughVenuesVersion'),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughvenuesversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throughvenuesversion',
            name='venue_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.VenueVersion'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_venue', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.VenueVersion'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_venue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_venueversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.VenueVersion'),
        ),
        migrations.AlterField(
            model_name='venueversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_venueversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='contributor',
            index_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='contributorversion',
            index_together=set([]),
        ),
        migrations.AddField(
            model_name='throughsubjectsversion',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='throughsubjectsversion',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='throughsubjectsversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AddField(
            model_name='throughsubjectsversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AddField(
            model_name='throughsubjectsversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughSubjects'),
        ),
        migrations.AddField(
            model_name='throughsubjectsversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughSubjectsVersion'),
        ),
        migrations.AddField(
            model_name='throughsubjectsversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughsubjectsversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='throughsubjectsversion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Subject'),
        ),
        migrations.AddField(
            model_name='throughsubjects',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='throughsubjects',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='throughsubjects',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AddField(
            model_name='throughsubjects',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AddField(
            model_name='throughsubjects',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughSubjects'),
        ),
        migrations.AddField(
            model_name='throughsubjects',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughSubjectsVersion'),
        ),
        migrations.AddField(
            model_name='throughsubjects',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughsubjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='throughsubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Subject'),
        ),
        migrations.AddField(
            model_name='throughsubjects',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughsubjects_version', to='share.ThroughSubjectsVersion'),
        ),
        migrations.AddField(
            model_name='abstractcreativework',
            name='subjects',
            field=share.models.fields.TypedManyToManyField(related_name='subjected_abstractcreativework', through='share.ThroughSubjects', to='share.Subject'),
        ),
        migrations.AddField(
            model_name='abstractcreativeworkversion',
            name='subjects',
            field=share.models.fields.TypedManyToManyField(related_name='subjected_abstractcreativeworkversion', through='share.ThroughSubjects', to='share.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectsynonym',
            unique_together=set([('subject', 'synonym')]),
        ),
    ]
