# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-28 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0029_source_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='canonical',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
