# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:27
from __future__ import unicode_literals

import db.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0029_source_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractagent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='abstractagentrelation',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='abstractagentrelationversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='abstractagentversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='abstractagentworkrelation',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='abstractagentworkrelationversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='abstractcreativework',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='abstractcreativeworkversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='abstractworkrelation',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='abstractworkrelationversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='agentidentifier',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentidentifierversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='awardversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='extradataversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='tagversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='throughawards',
            options={'base_manager_name': 'objects', 'verbose_name_plural': 'through awards'},
        ),
        migrations.AlterModelOptions(
            name='throughawardsversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',), 'verbose_name_plural': 'through awards'},
        ),
        migrations.AlterModelOptions(
            name='throughcontributor',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='throughcontributorversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='throughsubjects',
            options={'base_manager_name': 'objects', 'verbose_name_plural': 'through subjects'},
        ),
        migrations.AlterModelOptions(
            name='throughsubjectsversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',), 'verbose_name_plural': 'through subjects'},
        ),
        migrations.AlterModelOptions(
            name='throughtags',
            options={'base_manager_name': 'objects', 'verbose_name_plural': 'through tags'},
        ),
        migrations.AlterModelOptions(
            name='throughtagsversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',), 'verbose_name_plural': 'through tags'},
        ),
        migrations.AlterModelOptions(
            name='workidentifier',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='workidentifierversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',)},
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AbstractAgentRelation'),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AbstractAgent'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AbstractAgentWorkRelation'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AbstractWorkRelation'),
        ),
        migrations.AlterField(
            model_name='agentidentifierversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AgentIdentifier'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.Award'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.Tag'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.ThroughAwards'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.ThroughContributor'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.ThroughSubjects'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.ThroughTags'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.WorkIdentifier'),
        ),
    ]
