# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0029_update_trigger_migrations_20160824_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='app_label',
            field=models.TextField(null=True),
        ),
        migrations.RunSQL(
            sql='''UPDATE
                share_rawdata
            SET
                app_label = REPLACE(share_shareuser.robot, 'providers.', '')
            FROM
                share_shareuser
            WHERE
                share_rawdata.source_id = share_shareuser.id;''',
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='app_label',
            field=models.TextField(db_index=True),
        ),
    ]
