# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:21
from __future__ import unicode_literals

import db.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0029_source_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractagentrelationversion',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='abstractagentversion',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='abstractagentworkrelationversion',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='abstractcreativeworkversion',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='abstractworkrelationversion',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='agentidentifier',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='extradataversion',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='throughawardsversion',
            options={'ordering': ('-date_modified',), 'verbose_name_plural': 'through awards'},
        ),
        migrations.AlterModelOptions(
            name='throughcontributorversion',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='throughsubjectsversion',
            options={'ordering': ('-date_modified',), 'verbose_name_plural': 'through subjects'},
        ),
        migrations.AlterModelOptions(
            name='throughtagsversion',
            options={'ordering': ('-date_modified',), 'verbose_name_plural': 'through tags'},
        ),
        migrations.AlterModelOptions(
            name='workidentifier',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AbstractAgentRelation'),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AbstractAgent'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AbstractAgentWorkRelation'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AbstractWorkRelation'),
        ),
        migrations.AlterField(
            model_name='agentidentifierversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.AgentIdentifier'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.Award'),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='started_by',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='started_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='change',
            name='change_set',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='changes', to='share.ChangeSet'),
        ),
        migrations.AlterField(
            model_name='change',
            name='model_type',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='change',
            name='target_type',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='target_change', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='change',
            name='target_version_type',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='target_version_change', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='normalized_data',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.NormalizedData'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.ExtraData'),
        ),
        migrations.AlterField(
            model_name='harvestlog',
            name='source_config',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='harvest_logs', to='share.SourceConfig'),
        ),
        migrations.AlterField(
            model_name='normalizeddata',
            name='raw',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.RawDatum'),
        ),
        migrations.AlterField(
            model_name='normalizeddata',
            name='source',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='providerregistration',
            name='submitted_by',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rawdatum',
            name='suid',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.SourceUniqueIdentifier'),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='created_by',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='source',
            name='user',
            field=models.OneToOneField(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourceconfig',
            name='harvester',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.Harvester'),
        ),
        migrations.AlterField(
            model_name='sourceconfig',
            name='source',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.Source'),
        ),
        migrations.AlterField(
            model_name='sourceconfig',
            name='transformer',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.Transformer'),
        ),
        migrations.AlterField(
            model_name='sourceuniqueidentifier',
            name='source_config',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.SourceConfig'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), to='share.Subject'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.Tag'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.ThroughAwards'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.ThroughContributor'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='subject',
            field=models.ForeignKey(on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='work_relations', to='share.Subject'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.ThroughSubjects'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='subject',
            field=models.ForeignKey(db_index=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.Subject'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.ThroughTags'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='persistent_id',
            field=models.ForeignKey(db_column='persistent_id', on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='versions', to='share.WorkIdentifier'),
        ),
    ]
