# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0030_rawdata_app_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='bibliographic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contributorversion',
            name='bibliographic',
            field=models.BooleanField(default=True),
        ),
    ]
