# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0030_source_canonical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractagent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='agentidentifier',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='agentidentifierversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date of ingress to SHARE.'),
        ),
    ]
