# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0031_auto_20170504_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractcreativework',
            options={'base_manager_name': 'objects', 'verbose_name_plural': 'Creative Works'},
        ),
        migrations.AlterModelOptions(
            name='abstractcreativeworkversion',
            options={'base_manager_name': 'objects', 'ordering': ('-date_modified',), 'verbose_name_plural': 'Creative Works'},
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='free_to_read_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='free_to_read_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
