# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 19:31
from __future__ import unicode_literals

from django.db import migrations
import share.models.indexes


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('share', '0031_auto_20170504_1957'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='throughawardsversion',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_throu_date_cr_8f80c0_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractcreativework',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_creat_date_cr_d52552_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractworkrelationversion',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_workr_date_cr_47fc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractagentrelation',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_agent_date_cr_fcaeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractcreativeworkversion',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_creat_date_cr_9e5692_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractagentrelationversion',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_agent_date_cr_4a1805_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractworkrelation',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_workr_date_cr_d5e3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_tag_date_cr_142b45_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractagentworkrelation',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_agent_date_cr_c8c876_idx'),
        ),
        migrations.AddIndex(
            model_name='throughsubjectsversion',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_throu_date_cr_2cd155_idx'),
        ),
        migrations.AddIndex(
            model_name='throughawards',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_throu_date_cr_95147a_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractagentversion',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_agent_date_cr_909c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='throughcontributorversion',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_throu_date_cr_27f904_idx'),
        ),
        migrations.AddIndex(
            model_name='throughcontributor',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_throu_date_cr_794bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_award_date_cr_8e581d_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractagent',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_agent_date_cr_32b0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractagentworkrelationversion',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_agent_date_cr_f9cc71_idx'),
        ),
        migrations.AddIndex(
            model_name='throughtags',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_throu_date_cr_87cf55_idx'),
        ),
        migrations.AddIndex(
            model_name='agentidentifier',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_agent_date_cr_942ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='throughtagsversion',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_throu_date_cr_b5b82e_idx'),
        ),
        migrations.AddIndex(
            model_name='workidentifier',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_worki_date_cr_de62a6_idx'),
        ),
        migrations.AddIndex(
            model_name='throughsubjects',
            index=share.models.indexes.ConcurrentIndex(fields=['date_created'], name='share_throu_date_cr_265276_idx'),
        ),
    ]
