# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0031_populate_rawdata_app_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='app_label',
            field=models.TextField(db_index=True),
        ),
    ]
