# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0032_update_trigger_migrations_20160827_1914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectsynonym',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subjectsynonym',
            name='subject',
        ),
        migrations.DeleteModel(
            name='SubjectSynonym',
        ),
    ]
