# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0032_auto_20170508_1753'),
        ('share', '0032_auto_20170508_1931'),
    ]

    operations = [
    ]
