# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0033_merge_20170509_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsesDataFrom',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('share.workrelation',),
        ),
        migrations.CreateModel(
            name='UsesDataFromVersion',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('share.workrelationversion',),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='type',
            field=models.CharField(choices=[('share.workrelation', 'work relation'), ('share.cites', 'cites'), ('share.compiles', 'compiles'), ('share.corrects', 'corrects'), ('share.discusses', 'discusses'), ('share.disputes', 'disputes'), ('share.documents', 'documents'), ('share.extends', 'extends'), ('share.isderivedfrom', 'is derived from'), ('share.ispartof', 'is part of'), ('share.issupplementto', 'is supplement to'), ('share.references', 'references'), ('share.repliesto', 'replies to'), ('share.retracts', 'retracts'), ('share.reviews', 'reviews'), ('share.usesdatafrom', 'uses data from')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='type',
            field=models.CharField(choices=[('share.workrelationversion', 'work relation version'), ('share.citesversion', 'cites version'), ('share.compilesversion', 'compiles version'), ('share.correctsversion', 'corrects version'), ('share.discussesversion', 'discusses version'), ('share.disputesversion', 'disputes version'), ('share.documentsversion', 'documents version'), ('share.extendsversion', 'extends version'), ('share.isderivedfromversion', 'is derived from version'), ('share.ispartofversion', 'is part of version'), ('share.issupplementtoversion', 'is supplement to version'), ('share.referencesversion', 'references version'), ('share.repliestoversion', 'replies to version'), ('share.retractsversion', 'retracts version'), ('share.reviewsversion', 'reviews version'), ('share.usesdatafromversion', 'uses data from version')], db_index=True, max_length=255),
        ),
    ]
