# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0033_auto_20160829_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailversion',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
