# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0034_auto_20160831_1544'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='change',
            index_together=set([('target_type', 'target_id'), ('node_id', 'change_set', 'target_type')]),
        ),
    ]
