# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0034_auto_20160831_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractcreativework',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abstractcreativeworkversion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
