# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def trust_system_user(apps, schema_editor):
    ShareUser = apps.get_model('share', 'ShareUser')
    Source = apps.get_model('share', 'Source')

    system_user = ShareUser.objects.get(username=settings.APPLICATION_USERNAME)
    system_user.is_trusted = True
    system_user.save()

    Source.objects.create(
        name=settings.APPLICATION_USERNAME,
        long_title='SHARE System',
        canonical=True,
        user=system_user,
    )


def distrust_system_user(apps, schema_editor):
    ShareUser = apps.get_model('share', 'ShareUser')
    ShareUser.objects.filter(username=settings.APPLICATION_USERNAME).update(is_trusted=False)


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0034_auto_20170512_2052'),
    ]

    operations = [
        migrations.RunPython(trust_system_user, distrust_system_user)
    ]
