# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0035_celery_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatum',
            name='datestamp',
            field=models.DateTimeField(help_text="The most relevant datetime that can be extracted from this RawDatum. This may be, but is not limitted to, a deletion, modification, publication, or creation datestamp. Ideally, this datetime should be appropriate for determining the chronological order it's data will be applied.", null=True),
        ),
    ]
