# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 21:10
from __future__ import unicode_literals

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models

import db.deletion


def improvenance_subjects(apps, schema_editor):
    Subject = apps.get_model('share', 'Subject')
    Taxonomy = apps.get_model('share', 'Taxonomy')
    ShareUser = apps.get_model('share', 'ShareUser')
    NormalizedData = apps.get_model('share', 'NormalizedData')

    central_taxonomy = Taxonomy.objects.get_or_create(name=settings.SUBJECTS_CENTRAL_TAXONOMY)

    if not Subject.objects.exists():
        return

    user = ShareUser.objects.get(username=settings.APPLICATION_USERNAME)
    normalized_data = NormalizedData.objects.create(
        source=user,
        data={
            '@graph': [
                {
                    '@id': '_:{}'.format(s.id),
                    '@type': 'subject',
                    'name': s.name,
                    'parent': None if s.parent_id is None else {'@id': '_:{}'.format(s.parent_id), '@type': 'subject'}
                } for s in Subject.objects.all()
            ]
        }
    )
    from share.tasks import DisambiguatorTask
    DisambiguatorTask().apply((user.id, normalized_data.id), throw=True)


def deprovenance_subjects(apps, schema_editor):
    NormalizedData = apps.get_model('share', 'NormalizedData')
    ChangeSet = apps.get_model('share', 'ChangeSet')
    Change = apps.get_model('share', 'Change')
    Subject = apps.get_model('share', 'Subject')
    ThroughSubjects = apps.get_model('share', 'ThroughSubjects')

    # TODO disable triggers
    Subject.objects.update(change_id=None, taxonomy_id=None)
    ThroughSubjects.objects.update(subject_version=None)
    ThroughSubjects.VersionModel.objects.update(subject_version=None)


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0036_subject_taxonomy_a'),
    ]

    operations = [
        migrations.RunPython(improvenance_subjects), #, deprovenance_subjects),
    ]
