# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0036_rawdatum_datestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGLock',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('locktype', models.TextField()),
                ('objid', models.IntegerField()),
                ('classid', models.IntegerField()),
            ],
            options={
                'db_table': 'pg_locks',
                'managed': False,
            },
        ),
    ]
