# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 21:24
from __future__ import unicode_literals

import db.deletion
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0037_subject_provenance'),
    ]

    operations = [
        # Null the fields left from the last migration
        migrations.AlterField(
            model_name='subject',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_subject', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_subject_version', to='share.SubjectVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='subject_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.SubjectVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='subject_version',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='+', to='share.SubjectVersion'),
        ),

        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('name', 'taxonomy')]),
        ),
    ]
