# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 18:09
from __future__ import unicode_literals

from django.db import migrations


def DeleteDuplicates(table, *keys):
    return migrations.RunSQL(sql='DELETE FROM share_{0} WHERE id in (SELECT id FROM share_{0} EXCEPT SELECT min(id) FROM share_{0} GROUP BY {1});'.format(table, ', '.join(keys)))


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0037_update_trigger_migrations_20160903_2022'),
    ]

    operations = [
        DeleteDuplicates('affiliation', 'person_id', 'entity_id'),

        DeleteDuplicates('association', 'entity_id', 'creative_work_id'),

        DeleteDuplicates('contributor', 'person_id', 'creative_work_id'),

        DeleteDuplicates('personemail', 'person_id', 'email_id'),

        DeleteDuplicates('throughawardentities', 'award_id', 'entity_id'),

        DeleteDuplicates('throughawards', 'award_id', 'creative_work_id'),

        DeleteDuplicates('throughidentifiers', 'person_id', 'identifier_id'),

        DeleteDuplicates('throughlinks', 'link_id', 'creative_work_id'),

        DeleteDuplicates('throughsubjects', 'subject_id', 'creative_work_id'),

        DeleteDuplicates('throughtags', 'tag_id', 'creative_work_id'),

        DeleteDuplicates('throughvenues', 'venue_id', 'creative_work_id'),
    ]
