# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def trust_system_user(apps, schema_editor):
    ShareUser = apps.get_model('share', 'ShareUser')
    Source = apps.get_model('share', 'Source')

    system_user = ShareUser.objects.get(username=settings.APPLICATION_USERNAME)
    system_user.is_trusted = True
    system_user.save()

    Source.objects.update_or_create(
        user=system_user,
        defaults={
            'name': settings.APPLICATION_USERNAME,
            'long_title': 'SHARE System',
            'canonical': True,
        }
    )


def distrust_system_user(apps, schema_editor):
    ShareUser = apps.get_model('share', 'ShareUser')

    system_user = ShareUser.objects.get(username=settings.APPLICATION_USERNAME)
    system_user.is_trusted = False
    system_user.save()

    system_user.source.canonical = False
    system_user.source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0038_auto_20170606_1857'),
    ]

    operations = [
        migrations.RunPython(trust_system_user, distrust_system_user)
    ]
