# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:57
from __future__ import unicode_literals

from django.db import migrations
import share.models.indexes


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('share', '0037_pglock'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='change',
            index=share.models.indexes.ConcurrentIndex(fields=['target_id', 'target_type'], name='share_chang_target__a2c32d_idx'),
        ),
    ]
