# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0038_auto_20170606_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceconfig',
            name='harvest_interval',
            field=models.DurationField(default=datetime.timedelta(1)),
        ),
    ]
