# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0038_auto_20170606_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('response_status_code', models.SmallIntegerField(blank=True, null=True)),
                ('response_elapsed_time', models.FloatField(blank=True, null=True)),
                ('response_exception', models.TextField(blank=True, null=True)),
                ('earliest_datestamp_config', models.DateField(blank=True, null=True)),
                ('base_url_config', models.TextField()),
                ('admin_note', models.TextField(blank=True)),
                ('grade', models.FloatField()),
                ('earliest_datestamp_source', models.DateField(blank=True, null=True)),
                ('earliest_datestamps_match', models.BooleanField(default=False)),
                ('base_url_source', models.TextField(blank=True, null=True)),
                ('base_urls_match', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceConfig')),
            ],
        ),
    ]
