# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0038_dedup_through_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together=set([('person', 'entity')]),
        ),
        migrations.AlterUniqueTogether(
            name='association',
            unique_together=set([('entity', 'creative_work')]),
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set([('person', 'creative_work')]),
        ),
        migrations.AlterUniqueTogether(
            name='personemail',
            unique_together=set([('email', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='throughawardentities',
            unique_together=set([('award', 'entity')]),
        ),
        migrations.AlterUniqueTogether(
            name='throughawards',
            unique_together=set([('award', 'creative_work')]),
        ),
        migrations.AlterUniqueTogether(
            name='throughidentifiers',
            unique_together=set([('person', 'identifier')]),
        ),
        migrations.AlterUniqueTogether(
            name='throughlinks',
            unique_together=set([('link', 'creative_work')]),
        ),
        migrations.AlterUniqueTogether(
            name='throughsubjects',
            unique_together=set([('subject', 'creative_work')]),
        ),
        migrations.AlterUniqueTogether(
            name='throughtags',
            unique_together=set([('tag', 'creative_work')]),
        ),
        migrations.AlterUniqueTogether(
            name='throughvenues',
            unique_together=set([('venue', 'creative_work')]),
        ),
    ]
