# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 21:12
from __future__ import unicode_literals

from django.db import migrations
import share.util.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0039_auto_20170614_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconfig',
            name='json_encrypt',
            field=share.util.fields.EncryptedJSONField(blank=True, null=True),
        ),
    ]
