# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 21:02
from __future__ import unicode_literals

from django.db import migrations
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0039_auto_20160909_1910')
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=share.models.fields.ShareURLField(db_index=True),
        ),
        migrations.AlterField(
            model_name='linkversion',
            name='url',
            field=share.models.fields.ShareURLField(db_index=True),
        ),
    ]
