# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def improvenance_subjects(apps, schema_editor):
    Subject = apps.get_model('share', 'Subject')
    ShareUser = apps.get_model('share', 'ShareUser')

    user = ShareUser.objects.get(username=settings.APPLICATION_USERNAME)

    if not Subject.objects.exists():
        return

    subjects = [
        {
            '@id': '_:{}'.format(s.id),
            '@type': 'subject',
            'name': s.name,
            'parent': None if s.parent_id is None else {'@id': '_:{}'.format(s.parent_id), '@type': 'subject'}
        } for s in Subject.objects.all()
    ]

    from share.util.ingester import Ingester
    Ingester(subjects).as_user(user).ingest()


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0039_subject_taxonomy_a'),
    ]

    operations = [
        migrations.RunPython(improvenance_subjects),
    ]
