# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0039_auto_20170614_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentIdentifierState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', share.models.fields.ShareURLField(unique=True)),
                ('host', models.TextField(editable=False)),
                ('scheme', models.TextField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRelationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Unknown', 'unknown'), ('Is Affiliated With', 'isaffiliatedwith'), ('Is Employed By', 'isemployedby'), ('Is Member Of', 'ismemberof')], db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AgentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Unknown', 'unknown'), ('Organization', 'organization'), ('Consortium', 'consortium'), ('Department', 'department'), ('Institution', 'institution'), ('Person', 'person')], db_index=True, max_length=255)),
                ('name', models.TextField(blank=True, db_index=True)),
                ('location', models.TextField(blank=True)),
                ('suffix', models.TextField(blank=True, null=True)),
                ('additional_name', models.TextField(blank=True, null=True)),
                ('family_name', models.TextField(blank=True, null=True)),
                ('given_name', models.TextField(blank=True, null=True)),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
            ],
        ),
        migrations.CreateModel(
            name='AgentWorkRelationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Unknown', 'unknown'), ('Contributor', 'contributor'), ('Creator', 'creator'), ('Principal Investigator', 'principalinvestigator'), ('Principal Investigator Contact', 'principalinvestigatorcontact'), ('Funder', 'funder'), ('Host', 'host'), ('Publisher', 'publisher')], db_index=True, max_length=255)),
                ('cited_as', models.TextField(blank=True)),
                ('order_cited', models.PositiveIntegerField(null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='share.AgentState')),
            ],
        ),
        migrations.CreateModel(
            name='AwardState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('award_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('uri', share.models.fields.ShareURLField(blank=True, null=True, unique=True)),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeWorkState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Unknown', 'unknown'), ('Data Set', 'dataset'), ('Patent', 'patent'), ('Poster', 'poster'), ('Presentation', 'presentation'), ('Publication', 'publication'), ('Article', 'article'), ('Book', 'book'), ('Conference Paper', 'conferencepaper'), ('Dissertation', 'dissertation'), ('Preprint', 'preprint'), ('Project', 'project'), ('Registration', 'registration'), ('Report', 'report'), ('Thesis', 'thesis'), ('Working Paper', 'workingpaper'), ('Repository', 'repository'), ('Retraction', 'retraction'), ('Software', 'software')], db_index=True, max_length=255)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Determines whether or not this record will be discoverable via search.')),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('free_to_read_type', share.models.fields.ShareURLField(blank=True)),
                ('free_to_read_date', models.DateTimeField(blank=True, null=True)),
                ('rights', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, help_text='The ISO 3166-1 alpha-2 country code indicating the language of this record.', null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('registration_type', models.TextField(blank=True, null=True)),
                ('withdrawn', models.NullBooleanField()),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
            ],
            options={
                'verbose_name_plural': 'Creative Works',
            },
        ),
        migrations.CreateModel(
            name='SubjectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
            ],
        ),
        migrations.CreateModel(
            name='TagState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughAwardsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AwardState')),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AgentWorkRelationState')),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughContributorState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AgentWorkRelationState')),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AgentWorkRelationState')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughSubjectsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relations', to='share.CreativeWorkState')),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='share.SubjectState')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughTagsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='share.CreativeWorkState')),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='share.TagState')),
            ],
        ),
        migrations.CreateModel(
            name='WorkIdentifierState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', share.models.fields.ShareURLField(unique=True)),
                ('host', models.TextField(editable=False)),
                ('scheme', models.TextField(editable=False, help_text='A prefix to URI indicating how the following data should be interpreted.')),
                ('creative_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='share.CreativeWorkState')),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRelationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Unknown', 'unknown'), ('Cites', 'cites'), ('Compiles', 'compiles'), ('Corrects', 'corrects'), ('Discusses', 'discusses'), ('Disputes', 'disputes'), ('Documents', 'documents'), ('Extends', 'extends'), ('Is Derived From', 'isderivedfrom'), ('Is Part Of', 'ispartof'), ('Is Supplement To', 'issupplementto'), ('References', 'references'), ('Replies To', 'repliesto'), ('Retracts', 'retracts'), ('Reviews', 'reviews'), ('Uses Data From', 'usesdatafrom')], db_index=True, max_length=255)),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_creative_work_relations', to='share.CreativeWorkState')),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_creative_work_relations', to='share.CreativeWorkState')),
            ],
        ),
        migrations.AddField(
            model_name='agentworkrelationstate',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_relations', to='share.CreativeWorkState'),
        ),
        migrations.AddField(
            model_name='agentworkrelationstate',
            name='source_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier'),
        ),
        migrations.AddField(
            model_name='agentrelationstate',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_agent_relations', to='share.AgentState'),
        ),
        migrations.AddField(
            model_name='agentrelationstate',
            name='source_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier'),
        ),
        migrations.AddField(
            model_name='agentrelationstate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_agent_relations', to='share.AgentState'),
        ),
        migrations.AddField(
            model_name='agentidentifierstate',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='share.AgentState'),
        ),
        migrations.AddField(
            model_name='agentidentifierstate',
            name='source_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier'),
        ),
        migrations.AlterIndexTogether(
            name='agentstate',
            index_together=set([('type', 'name')]),
        ),
    ]
