# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 20:09
from __future__ import unicode_literals

from django.db import migrations
import share.models.indexes


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('share', '0040_rawdatum_no_change'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rawdatum',
            index=share.models.indexes.ConcurrentIndex(fields=['no_output'], name='share_rawda_no_outp_f0330f_idx'),
        ),
    ]
