# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0039_auto_20170614_1825'),
        ('share', '0041_subject_taxonomy_b'),
    ]

    operations = [
    ]
