# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import share.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0041_shareuser_is_trusted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_personidentifier', to='share.Change')),
                ('extra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
            ],
        ),
        migrations.CreateModel(
            name='PersonIdentifierVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_personidentifierversion', to='share.Change')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
            ],
            options={
                'db_table': None,
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.TextField(blank=True, choices=[('is_parent_to', ''), ('is_supplemented_by', ''), ('is_derived_from', ''), ('cites', 'http://purl.org/spar/cito/cites'), ('agrees_with', 'http://purl.org/spar/cito/agreesWith'), ('cites_as_authority', 'http://purl.org/spar/cito/citesAsAuthority'), ('cites_as_data_source', 'http://purl.org/spar/cito/citesAsDataSource'), ('cites_as_evidence', 'http://purl.org/spar/cito/citesAsEvidence'), ('cites_as_metadata_document', 'http://purl.org/spar/cito/citesAsMetadataDocument'), ('cites_as_potential_solution', 'http://purl.org/spar/cito/citesAsPotentialSolution'), ('cites_as_recommended_reading', 'http://purl.org/spar/cito/citesAsRecommendedReading'), ('cites_as_related', 'http://purl.org/spar/cito/citesAsRelated'), ('cites_as_source_document', 'http://purl.org/spar/cito/citesAsSourceDocument'), ('cites_for_information', 'http://purl.org/spar/cito/citesForInformation'), ('compiles', 'http://purl.org/spar/cito/compiles'), ('confirms', 'http://purl.org/spar/cito/confirms'), ('contains_assertion_from', 'http://purl.org/spar/cito/containsAssertionFrom'), ('corrects', 'http://purl.org/spar/cito/corrects'), ('credits', 'http://purl.org/spar/cito/credits'), ('critiques', 'http://purl.org/spar/cito/critiques'), ('derides', 'http://purl.org/spar/cito/derides'), ('describes', 'http://purl.org/spar/cito/describes'), ('disagrees_with', 'http://purl.org/spar/cito/disagreesWith'), ('discusses', 'http://purl.org/spar/cito/discusses'), ('disputes', 'http://purl.org/spar/cito/disputes'), ('documents', 'http://purl.org/spar/cito/documents'), ('extends', 'http://purl.org/spar/cito/extends'), ('includes_excerpt_from', 'http://purl.org/spar/cito/includesExcerptFrom'), ('includes_quotation_from', 'http://purl.org/spar/cito/includesQuotationFrom'), ('obtains_background_from', 'http://purl.org/spar/cito/obtainsBackgroundFrom'), ('obtains_support_from', 'http://purl.org/spar/cito/obtainsSupportFrom'), ('parodies', 'http://purl.org/spar/cito/parodies'), ('plagiarizes', 'http://purl.org/spar/cito/plagiarizes'), ('qualifies', 'http://purl.org/spar/cito/qualifies'), ('refutes', 'http://purl.org/spar/cito/refutes'), ('replies_to', 'http://purl.org/spar/cito/repliesTo'), ('retracts', 'http://purl.org/spar/cito/retracts'), ('reviews', 'http://purl.org/spar/cito/reviews'), ('ridicules', 'http://purl.org/spar/cito/ridicules'), ('speculates_on', 'http://purl.org/spar/cito/speculatesOn'), ('supports', 'http://purl.org/spar/cito/supports'), ('updates', 'http://purl.org/spar/cito/updates'), ('uses_conclusions_from', 'http://purl.org/spar/cito/usesConclusionsFrom'), ('uses_data_from', 'http://purl.org/spar/cito/usesDataFrom'), ('uses_method_in', 'http://purl.org/spar/cito/usesMethodIn')])),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_relation', to='share.Change')),
                ('extra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
            ],
        ),
        migrations.CreateModel(
            name='RelationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('relation_type', models.TextField(blank=True, choices=[('is_parent_to', ''), ('is_supplemented_by', ''), ('is_derived_from', ''), ('cites', 'http://purl.org/spar/cito/cites'), ('agrees_with', 'http://purl.org/spar/cito/agreesWith'), ('cites_as_authority', 'http://purl.org/spar/cito/citesAsAuthority'), ('cites_as_data_source', 'http://purl.org/spar/cito/citesAsDataSource'), ('cites_as_evidence', 'http://purl.org/spar/cito/citesAsEvidence'), ('cites_as_metadata_document', 'http://purl.org/spar/cito/citesAsMetadataDocument'), ('cites_as_potential_solution', 'http://purl.org/spar/cito/citesAsPotentialSolution'), ('cites_as_recommended_reading', 'http://purl.org/spar/cito/citesAsRecommendedReading'), ('cites_as_related', 'http://purl.org/spar/cito/citesAsRelated'), ('cites_as_source_document', 'http://purl.org/spar/cito/citesAsSourceDocument'), ('cites_for_information', 'http://purl.org/spar/cito/citesForInformation'), ('compiles', 'http://purl.org/spar/cito/compiles'), ('confirms', 'http://purl.org/spar/cito/confirms'), ('contains_assertion_from', 'http://purl.org/spar/cito/containsAssertionFrom'), ('corrects', 'http://purl.org/spar/cito/corrects'), ('credits', 'http://purl.org/spar/cito/credits'), ('critiques', 'http://purl.org/spar/cito/critiques'), ('derides', 'http://purl.org/spar/cito/derides'), ('describes', 'http://purl.org/spar/cito/describes'), ('disagrees_with', 'http://purl.org/spar/cito/disagreesWith'), ('discusses', 'http://purl.org/spar/cito/discusses'), ('disputes', 'http://purl.org/spar/cito/disputes'), ('documents', 'http://purl.org/spar/cito/documents'), ('extends', 'http://purl.org/spar/cito/extends'), ('includes_excerpt_from', 'http://purl.org/spar/cito/includesExcerptFrom'), ('includes_quotation_from', 'http://purl.org/spar/cito/includesQuotationFrom'), ('obtains_background_from', 'http://purl.org/spar/cito/obtainsBackgroundFrom'), ('obtains_support_from', 'http://purl.org/spar/cito/obtainsSupportFrom'), ('parodies', 'http://purl.org/spar/cito/parodies'), ('plagiarizes', 'http://purl.org/spar/cito/plagiarizes'), ('qualifies', 'http://purl.org/spar/cito/qualifies'), ('refutes', 'http://purl.org/spar/cito/refutes'), ('replies_to', 'http://purl.org/spar/cito/repliesTo'), ('retracts', 'http://purl.org/spar/cito/retracts'), ('reviews', 'http://purl.org/spar/cito/reviews'), ('ridicules', 'http://purl.org/spar/cito/ridicules'), ('speculates_on', 'http://purl.org/spar/cito/speculatesOn'), ('supports', 'http://purl.org/spar/cito/supports'), ('updates', 'http://purl.org/spar/cito/updates'), ('uses_conclusions_from', 'http://purl.org/spar/cito/usesConclusionsFrom'), ('uses_data_from', 'http://purl.org/spar/cito/usesDataFrom'), ('uses_method_in', 'http://purl.org/spar/cito/usesMethodIn')])),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_relationversion', to='share.Change')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
            ],
            options={
                'db_table': None,
            },
        ),
        migrations.CreateModel(
            name='WorkIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_workidentifier', to='share.Change')),
            ],
        ),
        migrations.CreateModel(
            name='WorkIdentifierVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_workidentifierversion', to='share.Change')),
            ],
            options={
                'db_table': None,
            },
        ),
        migrations.RemoveField(
            model_name='link',
            name='change',
        ),
        migrations.RemoveField(
            model_name='link',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='link',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='link',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='link',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='link',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='link',
            name='version',
        ),
        migrations.RemoveField(
            model_name='linkversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='linkversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='linkversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='linkversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='linkversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='linkversion',
            name='sources',
        ),
        migrations.AlterUniqueTogether(
            name='throughidentifiers',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='change',
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='identifier_version',
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='person',
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='person_version',
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughidentifiers',
            name='version',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='identifier_version',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='person',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='person_version',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='sources',
        ),
        migrations.AlterUniqueTogether(
            name='throughlinks',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='change',
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='creative_work',
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='creative_work_version',
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='link',
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='link_version',
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughlinks',
            name='version',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='creative_work',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='creative_work_version',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='link',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='link_version',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='link_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='links',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='link_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='links',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='identifierversion',
            name='base_url',
        ),
        migrations.AddField(
            model_name='abstractcreativework',
            name='is_stub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abstractcreativeworkversion',
            name='is_stub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='identifier_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.PersonIdentifier', to='share.IdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='person',
            name='identifiers',
            field=share.models.fields.TypedManyToManyField(through='share.PersonIdentifier', to='share.Identifier'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='identifier_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.PersonIdentifier', to='share.IdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='personversion',
            name='identifiers',
            field=share.models.fields.TypedManyToManyField(through='share.PersonIdentifier', to='share.Identifier'),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='LinkVersion',
        ),
        migrations.DeleteModel(
            name='ThroughIdentifiers',
        ),
        migrations.DeleteModel(
            name='ThroughIdentifiersVersion',
        ),
        migrations.DeleteModel(
            name='ThroughLinks',
        ),
        migrations.DeleteModel(
            name='ThroughLinksVersion',
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Identifier'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='identifier_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.IdentifierVersion'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkIdentifier'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_workidentifierversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Identifier'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='identifier_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.IdentifierVersion'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkIdentifier'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_workidentifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_workidentifier_version', to='share.WorkIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='relationversion',
            name='object_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationversions', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='relationversion',
            name='object_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationversions', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='relationversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.Relation'),
        ),
        migrations.AddField(
            model_name='relationversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.RelationVersion'),
        ),
        migrations.AddField(
            model_name='relationversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_relationversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationversion',
            name='subject_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationversions', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='relationversion',
            name='subject_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationversions', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='relation',
            name='object_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='relation',
            name='object_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='relation',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.Relation'),
        ),
        migrations.AddField(
            model_name='relation',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.RelationVersion'),
        ),
        migrations.AddField(
            model_name='relation',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relation',
            name='subject_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='relation',
            name='subject_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='relation',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_relation_version', to='share.RelationVersion'),
        ),
        migrations.AddField(
            model_name='personidentifierversion',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Identifier'),
        ),
        migrations.AddField(
            model_name='personidentifierversion',
            name='identifier_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.IdentifierVersion'),
        ),
        migrations.AddField(
            model_name='personidentifierversion',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Person'),
        ),
        migrations.AddField(
            model_name='personidentifierversion',
            name='person_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.PersonVersion'),
        ),
        migrations.AddField(
            model_name='personidentifierversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.PersonIdentifier'),
        ),
        migrations.AddField(
            model_name='personidentifierversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.PersonIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='personidentifierversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_personidentifierversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personidentifier',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Identifier'),
        ),
        migrations.AddField(
            model_name='personidentifier',
            name='identifier_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.IdentifierVersion'),
        ),
        migrations.AddField(
            model_name='personidentifier',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Person'),
        ),
        migrations.AddField(
            model_name='personidentifier',
            name='person_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.PersonVersion'),
        ),
        migrations.AddField(
            model_name='personidentifier',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.PersonIdentifier'),
        ),
        migrations.AddField(
            model_name='personidentifier',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.PersonIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='personidentifier',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_personidentifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personidentifier',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_personidentifier_version', to='share.PersonIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='abstractcreativework',
            name='identifier_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.WorkIdentifier', to='share.IdentifierVersion'),
        ),
        migrations.AddField(
            model_name='abstractcreativework',
            name='identifiers',
            field=share.models.fields.TypedManyToManyField(through='share.WorkIdentifier', to='share.Identifier'),
        ),
        migrations.AddField(
            model_name='abstractcreativework',
            name='related_work_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Relation', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='abstractcreativework',
            name='related_works',
            field=share.models.fields.TypedManyToManyField(through='share.Relation', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='abstractcreativeworkversion',
            name='identifier_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.WorkIdentifier', to='share.IdentifierVersion'),
        ),
        migrations.AddField(
            model_name='abstractcreativeworkversion',
            name='identifiers',
            field=share.models.fields.TypedManyToManyField(through='share.WorkIdentifier', to='share.Identifier'),
        ),
        migrations.AddField(
            model_name='abstractcreativeworkversion',
            name='related_work_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Relation', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='abstractcreativeworkversion',
            name='related_works',
            field=share.models.fields.TypedManyToManyField(through='share.Relation', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterUniqueTogether(
            name='workidentifier',
            unique_together=set([('creative_work', 'identifier')]),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set([('subject_work', 'object_work', 'relation_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='personidentifier',
            unique_together=set([('person', 'identifier')]),
        ),
    ]
