# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0042_merge_20170620_1330'),
        ('share', '0039_sourcestat'),
    ]

    operations = [
    ]
