# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0042_merge_20170620_1330'),
        ('share', '0040_sourceconfig_json_encrypt'),
    ]

    operations = [
    ]
