# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0043_merge_20170626_1516'),
        ('share', '0041_no_change_index'),
    ]

    operations = [
    ]
