# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 20:11
from __future__ import unicode_literals

from django.db import migrations
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0043_merge_20170626_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconfig',
            name='json_encrypt',
            field=share.models.fields.EncryptedJSONField(blank=True, null=True),
        ),
    ]
