# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 15:47
from __future__ import unicode_literals

from django.db import migrations
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0045_subject_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uri',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('uri', 'taxonomy'), ('name', 'taxonomy')]),
        ),
    ]
