# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 16:02
from __future__ import unicode_literals

from django.db import migrations
import share.models.fields
import share.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0045_auto_20160927_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='awardversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='emailversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='entityversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='extradataversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='identifierversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='linkversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='tagversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughidentifiersversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughlinksversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughsubjectsversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughtagsversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughvenuesversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='venueversion',
            name='sources',
        )
    ]
