# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 19:48
from __future__ import unicode_literals

from django.db import migrations
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0045_sourceconfig_json_encrypt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconfig',
            name='private_harvester_kwargs',
            field=share.models.fields.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceconfig',
            name='private_transformer_kwargs',
            field=share.models.fields.EncryptedJSONField(blank=True, null=True),
        ),
    ]
