# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import share.models.fields
import share.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0046_source_dedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerregistration',
            name='admin_notes',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='normalizeddata',
            name='normalized_data',
            field=share.models.fields.DateTimeAwareJSONField(validators=[share.models.validators.JSONLDValidator()]),
        ),
        migrations.AlterField(
            model_name='providerregistration',
            name='source_additional_info',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='providerregistration',
            name='source_description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='providerregistration',
            name='source_disallowed_sets',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='providerregistration',
            name='source_documentation',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='providerregistration',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'implemented'), (3, 'rejected'), (4, 'contact required'), (5, 'awaiting response')], default=0),
        ),
    ]
