# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:52
from __future__ import unicode_literals

from django.db import migrations
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0047_auto_20171019_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconfig',
            name='private_harvester_kwargs',
            field=share.models.fields.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceconfig',
            name='private_transformer_kwargs',
            field=share.models.fields.EncryptedJSONField(blank=True, null=True),
        ),
    ]
