# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0047_jobs'),
        ('share', '0047_auto_20171019_2018'),
    ]

    operations = [
    ]
