# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 18:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import share.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0048_update_trigger_migrations_20161003_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractEntity',
            fields=[
                ('type', models.CharField(db_index=True, max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('family_name', models.TextField(blank=True, db_index=True, null=True)),
                ('given_name', models.TextField(blank=True, db_index=True, null=True)),
                ('additional_name', models.TextField(blank=True, db_index=True, null=True)),
                ('suffix', models.TextField(blank=True, db_index=True, null=True)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_abstractentity', to='share.Change')),
                ('extra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
            ],
            options={
                'verbose_name_plural': 'AbstractEntities',
            },
        ),
        migrations.CreateModel(
            name='AbstractEntityVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=255)),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('name', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('family_name', models.TextField(blank=True, db_index=True, null=True)),
                ('given_name', models.TextField(blank=True, db_index=True, null=True)),
                ('additional_name', models.TextField(blank=True, db_index=True, null=True)),
                ('suffix', models.TextField(blank=True, db_index=True, null=True)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_abstractentityversion', to='share.Change')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
            ],
            options={
                'verbose_name_plural': 'AbstractEntities',
                'db_table': None,
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cited_name', models.TextField(blank=True)),
                ('bibliographic', models.BooleanField(default=True)),
                ('order_cited', models.PositiveIntegerField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('cited_name', models.TextField(blank=True)),
                ('bibliographic', models.BooleanField(default=True)),
                ('order_cited', models.PositiveIntegerField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': None,
            },
        ),
        migrations.CreateModel(
            name='EntityIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', share.models.fields.ShareURLField(unique=True)),
                ('host', models.TextField(editable=False)),
                ('scheme', models.TextField(editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_entityidentifier', to='share.Change')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entityidentifiers', to='share.AbstractEntity')),
                ('entity_version', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='entityidentifiers', to='share.AbstractEntityVersion')),
                ('extra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
                ('same_as', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EntityIdentifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityIdentifierVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('uri', share.models.fields.ShareURLField()),
                ('host', models.TextField(editable=False)),
                ('scheme', models.TextField(editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_entityidentifierversion', to='share.Change')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entityidentifierversions', to='share.AbstractEntity')),
                ('entity_version', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='entityidentifierversions', to='share.AbstractEntityVersion')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
                ('same_as', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EntityIdentifier')),
                ('same_as_version', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EntityIdentifierVersion')),
                ('sources', models.ManyToManyField(editable=False, related_name='source_entityidentifierversion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ('-date_modified',),
            },
        ),
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_entityrelation', to='share.Change')),
                ('extra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_entityrelations', to='share.AbstractEntity')),
                ('from_entity_version', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_entityrelations', to='share.AbstractEntityVersion')),
            ],
        ),
        migrations.CreateModel(
            name='EntityRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('uris', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, editable=False, size=None)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='share.EntityRelationType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityRelationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_entityrelationversion', to='share.Change')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_entityrelationversions', to='share.AbstractEntity')),
                ('from_entity_version', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_entityrelationversions', to='share.AbstractEntityVersion')),
                ('relation_type', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.EntityRelationType')),
                ('same_as', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EntityRelation')),
                ('same_as_version', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EntityRelationVersion')),
                ('sources', models.ManyToManyField(editable=False, related_name='source_entityrelationversion', to=settings.AUTH_USER_MODEL)),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_entityrelationversions', to='share.AbstractEntity')),
                ('to_entity_version', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_entityrelationversions', to='share.AbstractEntityVersion')),
            ],
            options={
                'db_table': None,
            },
        ),
        migrations.CreateModel(
            name='ThroughContributionAwards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThroughContributionAwardsVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': None,
            },
        ),
        migrations.CreateModel(
            name='WorkIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', share.models.fields.ShareURLField(unique=True)),
                ('host', models.TextField(editable=False)),
                ('scheme', models.TextField(editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_workidentifier', to='share.Change')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkIdentifierVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('uri', share.models.fields.ShareURLField()),
                ('host', models.TextField(editable=False)),
                ('scheme', models.TextField(editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_workidentifierversion', to='share.Change')),
            ],
            options={
                'abstract': False,
                'ordering': ('-date_modified',),
            },
        ),
        migrations.CreateModel(
            name='WorkRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_workrelation', to='share.Change')),
                ('extra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('uris', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, editable=False, size=None)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='share.WorkRelationType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkRelationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=10)),
                ('persistent_id', models.PositiveIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('change', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_workrelationversion', to='share.Change')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData')),
                ('extra_version', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion')),
            ],
            options={
                'db_table': None,
            },
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='change',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='entity_version',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='person_version',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='version',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='entity_version',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='person',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='person_version',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='affiliationversion',
            name='sources',
        ),
        migrations.AlterUniqueTogether(
            name='association',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='association',
            name='change',
        ),
        migrations.RemoveField(
            model_name='association',
            name='creative_work',
        ),
        migrations.RemoveField(
            model_name='association',
            name='creative_work_version',
        ),
        migrations.RemoveField(
            model_name='association',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='association',
            name='entity_version',
        ),
        migrations.RemoveField(
            model_name='association',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='association',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='association',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='association',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='association',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='association',
            name='version',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='creative_work',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='creative_work_version',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='entity_version',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='associationversion',
            name='sources',
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='change',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='creative_work',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='creative_work_version',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='person',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='person_version',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='version',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='creative_work',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='creative_work_version',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='person',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='person_version',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='contributorversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifier',
            name='change',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifier',
            name='creative_work',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifier',
            name='creative_work_version',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifier',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifier',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifier',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifier',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifier',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifier',
            name='version',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifierversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifierversion',
            name='creative_work',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifierversion',
            name='creative_work_version',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifierversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifierversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifierversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifierversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='creativeworkidentifierversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='email',
            name='change',
        ),
        migrations.RemoveField(
            model_name='email',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='email',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='email',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='email',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='email',
            name='version',
        ),
        migrations.RemoveField(
            model_name='emailversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='emailversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='emailversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='emailversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='emailversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='emailversion',
            name='sources',
        ),
        migrations.AlterIndexTogether(
            name='entity',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='entity',
            name='affiliation_versions',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='affiliations',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='change',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='version',
        ),
        migrations.AlterIndexTogether(
            name='entityversion',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='entityversion',
            name='affiliation_versions',
        ),
        migrations.RemoveField(
            model_name='entityversion',
            name='affiliations',
        ),
        migrations.RemoveField(
            model_name='entityversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='entityversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='entityversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='entityversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='entityversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='entityversion',
            name='sources',
        ),
        migrations.AlterIndexTogether(
            name='person',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='person',
            name='affiliation_versions',
        ),
        migrations.RemoveField(
            model_name='person',
            name='affiliations',
        ),
        migrations.RemoveField(
            model_name='person',
            name='change',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email_versions',
        ),
        migrations.RemoveField(
            model_name='person',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='person',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='person',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='person',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='person',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='person',
            name='version',
        ),
        migrations.AlterUniqueTogether(
            name='personemail',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='change',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='email_version',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='person_version',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='version',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='email_version',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='person_version',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='personemailversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='personidentifier',
            name='change',
        ),
        migrations.RemoveField(
            model_name='personidentifier',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='personidentifier',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='personidentifier',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personidentifier',
            name='person_version',
        ),
        migrations.RemoveField(
            model_name='personidentifier',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='personidentifier',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='personidentifier',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='personidentifier',
            name='version',
        ),
        migrations.RemoveField(
            model_name='personidentifierversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='personidentifierversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='personidentifierversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='personidentifierversion',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personidentifierversion',
            name='person_version',
        ),
        migrations.RemoveField(
            model_name='personidentifierversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='personidentifierversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='personidentifierversion',
            name='sources',
        ),
        migrations.AlterIndexTogether(
            name='personversion',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='affiliation_versions',
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='affiliations',
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='email_versions',
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='personversion',
            name='sources',
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='relation',
            name='change',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='from_work',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='from_work_version',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='to_work',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='to_work_version',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='version',
        ),
        migrations.RemoveField(
            model_name='relationversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='relationversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='relationversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='relationversion',
            name='from_work',
        ),
        migrations.RemoveField(
            model_name='relationversion',
            name='from_work_version',
        ),
        migrations.RemoveField(
            model_name='relationversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='relationversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='relationversion',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='relationversion',
            name='to_work',
        ),
        migrations.RemoveField(
            model_name='relationversion',
            name='to_work_version',
        ),
        migrations.AlterUniqueTogether(
            name='throughawardentities',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='award',
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='award_version',
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='change',
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='entity_version',
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughawardentities',
            name='version',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='award',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='award_version',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='entity_version',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='throughawardentitiesversion',
            name='sources',
        ),
        migrations.AlterUniqueTogether(
            name='throughawards',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='award',
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='award_version',
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='change',
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='creative_work',
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='creative_work_version',
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='throughawards',
            name='version',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='award',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='award_version',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='change',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='creative_work',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='creative_work_version',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='extra_version',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='same_as',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='same_as_version',
        ),
        migrations.RemoveField(
            model_name='throughawardsversion',
            name='sources',
        ),
        migrations.DeleteModel(
            name='Funder',
        ),
        migrations.DeleteModel(
            name='FunderVersion',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='PublisherVersion',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='award_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='funder_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='funders',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='institution_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='organization_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='publisher_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativework',
            name='publishers',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='award_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='funder_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='funders',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='institution_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='organization_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='publisher_versions',
        ),
        migrations.RemoveField(
            model_name='abstractcreativeworkversion',
            name='publishers',
        ),
        migrations.RemoveField(
            model_name='award',
            name='entitie_versions',
        ),
        migrations.RemoveField(
            model_name='award',
            name='entities',
        ),
        migrations.RemoveField(
            model_name='awardversion',
            name='entitie_versions',
        ),
        migrations.RemoveField(
            model_name='awardversion',
            name='entities',
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='contributor_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Contribution', to='share.AbstractEntityVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='contributors',
            field=share.models.fields.TypedManyToManyField(through='share.Contribution', to='share.AbstractEntity'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='related_work_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.WorkRelation', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='related_works',
            field=share.models.fields.TypedManyToManyField(through='share.WorkRelation', to='share.AbstractCreativeWork'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='contributor_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.Contribution', to='share.AbstractEntityVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='contributors',
            field=share.models.fields.TypedManyToManyField(through='share.Contribution', to='share.AbstractEntity'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='related_work_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.WorkRelation', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='related_works',
            field=share.models.fields.TypedManyToManyField(through='share.WorkRelation', to='share.AbstractCreativeWork'),
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='AffiliationVersion',
        ),
        migrations.DeleteModel(
            name='Association',
        ),
        migrations.DeleteModel(
            name='AssociationVersion',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='ContributorVersion',
        ),
        migrations.DeleteModel(
            name='CreativeWorkIdentifier',
        ),
        migrations.DeleteModel(
            name='CreativeWorkIdentifierVersion',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='EmailVersion',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='EntityVersion',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonEmail',
        ),
        migrations.DeleteModel(
            name='PersonEmailVersion',
        ),
        migrations.DeleteModel(
            name='PersonIdentifier',
        ),
        migrations.DeleteModel(
            name='PersonIdentifierVersion',
        ),
        migrations.DeleteModel(
            name='PersonVersion',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.DeleteModel(
            name='RelationVersion',
        ),
        migrations.DeleteModel(
            name='ThroughAwardEntities',
        ),
        migrations.DeleteModel(
            name='ThroughAwardEntitiesVersion',
        ),
        migrations.DeleteModel(
            name='ThroughAwards',
        ),
        migrations.DeleteModel(
            name='ThroughAwardsVersion',
        ),
        migrations.AddField(
            model_name='workrelationversion',
            name='from_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_workrelationversions', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='workrelationversion',
            name='from_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_workrelationversions', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='workrelationversion',
            name='relation_type',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.WorkRelationType'),
        ),
        migrations.AddField(
            model_name='workrelationversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkRelation'),
        ),
        migrations.AddField(
            model_name='workrelationversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkRelationVersion'),
        ),
        migrations.AddField(
            model_name='workrelationversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_workrelationversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrelationversion',
            name='to_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_workrelationversions', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='workrelationversion',
            name='to_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_workrelationversions', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='workrelation',
            name='from_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_workrelations', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='workrelation',
            name='from_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_workrelations', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='workrelation',
            name='relation_type',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.WorkRelationType'),
        ),
        migrations.AddField(
            model_name='workrelation',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkRelation'),
        ),
        migrations.AddField(
            model_name='workrelation',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkRelationVersion'),
        ),
        migrations.AddField(
            model_name='workrelation',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_workrelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrelation',
            name='to_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_workrelations', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='workrelation',
            name='to_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_workrelations', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='workrelation',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_workrelation_version', to='share.WorkRelationVersion'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workidentifierversions', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='workidentifierversions', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkIdentifier'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='workidentifierversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_workidentifierversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workidentifiers', to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='workidentifiers', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkIdentifier'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.WorkIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_workidentifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_workidentifier_version', to='share.WorkIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='throughcontributionawardsversion',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Award'),
        ),
        migrations.AddField(
            model_name='throughcontributionawardsversion',
            name='award_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AwardVersion'),
        ),
        migrations.AddField(
            model_name='throughcontributionawardsversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughcontributionawardsversion', to='share.Change'),
        ),
        migrations.AddField(
            model_name='throughcontributionawardsversion',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Contribution'),
        ),
        migrations.AddField(
            model_name='throughcontributionawardsversion',
            name='contribution_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.ContributionVersion'),
        ),
        migrations.AddField(
            model_name='throughcontributionawardsversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AddField(
            model_name='throughcontributionawardsversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AddField(
            model_name='throughcontributionawardsversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughContributionAwards'),
        ),
        migrations.AddField(
            model_name='throughcontributionawardsversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughContributionAwardsVersion'),
        ),
        migrations.AddField(
            model_name='throughcontributionawardsversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughcontributionawardsversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Award'),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='award_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AwardVersion'),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_throughcontributionawards', to='share.Change'),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Contribution'),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='contribution_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.ContributionVersion'),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughContributionAwards'),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ThroughContributionAwardsVersion'),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_throughcontributionawards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='throughcontributionawards',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_throughcontributionawards_version', to='share.ThroughContributionAwardsVersion'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='relation_type',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.EntityRelationType'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EntityRelation'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EntityRelationVersion'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_entityrelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='to_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_entityrelations', to='share.AbstractEntity'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='to_entity_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_entityrelations', to='share.AbstractEntityVersion'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_entityrelation_version', to='share.EntityRelationVersion'),
        ),
        migrations.AddField(
            model_name='entityidentifier',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.EntityIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='entityidentifier',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_entityidentifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entityidentifier',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_entityidentifier_version', to='share.EntityIdentifierVersion'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='award_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughContributionAwards', to='share.AwardVersion'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='awards',
            field=share.models.fields.TypedManyToManyField(through='share.ThroughContributionAwards', to='share.Award'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_contributionversion', to='share.Change'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AbstractEntity'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='entity_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractEntityVersion'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='extra_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.Contribution'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ContributionVersion'),
        ),
        migrations.AddField(
            model_name='contributionversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_contributionversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='award_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.ThroughContributionAwards', to='share.AwardVersion'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='awards',
            field=share.models.fields.TypedManyToManyField(through='share.ThroughContributionAwards', to='share.Award'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='change',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='affected_contribution', to='share.Change'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWork'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='creative_work_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.AbstractEntity'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='entity_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractEntityVersion'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraData'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='extra_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ExtraDataVersion'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.Contribution'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.ContributionVersion'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_contribution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_contribution_version', to='share.ContributionVersion'),
        ),
        migrations.AddField(
            model_name='abstractentityversion',
            name='related_entitie_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.EntityRelation', to='share.AbstractEntityVersion'),
        ),
        migrations.AddField(
            model_name='abstractentityversion',
            name='related_entities',
            field=share.models.fields.TypedManyToManyField(through='share.EntityRelation', to='share.AbstractEntity'),
        ),
        migrations.AddField(
            model_name='abstractentityversion',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AbstractEntity'),
        ),
        migrations.AddField(
            model_name='abstractentityversion',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AbstractEntityVersion'),
        ),
        migrations.AddField(
            model_name='abstractentityversion',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_abstractentityversion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abstractentity',
            name='related_entitie_versions',
            field=share.models.fields.TypedManyToManyField(editable=False, through='share.EntityRelation', to='share.AbstractEntityVersion'),
        ),
        migrations.AddField(
            model_name='abstractentity',
            name='related_entities',
            field=share.models.fields.TypedManyToManyField(through='share.EntityRelation', to='share.AbstractEntity'),
        ),
        migrations.AddField(
            model_name='abstractentity',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AbstractEntity'),
        ),
        migrations.AddField(
            model_name='abstractentity',
            name='same_as_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='share.AbstractEntityVersion'),
        ),
        migrations.AddField(
            model_name='abstractentity',
            name='sources',
            field=models.ManyToManyField(editable=False, related_name='source_abstractentity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abstractentity',
            name='version',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share_abstractentity_version', to='share.AbstractEntityVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='workrelation',
            unique_together=set([('from_work', 'to_work', 'relation_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='throughcontributionawards',
            unique_together=set([('contribution', 'award')]),
        ),
        migrations.AlterUniqueTogether(
            name='entityrelation',
            unique_together=set([('from_entity', 'to_entity', 'relation_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together=set([('entity', 'creative_work')]),
        ),
        migrations.AlterIndexTogether(
            name='abstractentityversion',
            index_together=set([('type', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='abstractentity',
            index_together=set([('type', 'name')]),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.abstractentity',),
        ),
        migrations.CreateModel(
            name='PersonVersion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('share.abstractentityversion',),
        ),
    ]
