# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0049_auto_20171121_2157'),
        ('share', '0048_auto_20171113_1852'),
    ]

    operations = [
    ]
