# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0047_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestjob',
            name='apply_changes_retries',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='normalized_data',
            field=models.ManyToManyField(related_name='ingest_jobs', to='share.NormalizedData'),
        ),
        migrations.AddField(
            model_name='normalizeddata',
            name='ingest_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingested_normalized_data', to='share.IngestJob'),
        ),
    ]
