# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import share.models.ingest


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0049_merge_20171103_1955'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sourceconfig',
            managers=[
                ('objects', share.models.ingest.SourceConfigManager('label')),
            ],
        ),
        migrations.AddField(
            model_name='harvestjob',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='retries',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='normalizeddata',
            name='ingest_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingested_normalized_data', to='share.IngestJob'),
        ),
    ]
