# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # CREATE INDEX CONCURRENTLY cannot be run in a txn

    dependencies = [
        ('share', '0049_jobs'),
    ]

    operations = [
        # Add the same index Django would, but concurrently
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='harvestjob',
                    name='error_type',
                    field=models.TextField(blank=True, db_index=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL([
                    'CREATE INDEX CONCURRENTLY "share_harvestlog_error_type_5968fb47" ON "share_harvestlog" ("error_type");',
                ], [
                    'DROP INDEX IF EXISTS "share_harvestlog_error_type_5968fb47", RESTRICT;'
                ])
            ]
        )
    ]
