# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0049_merge_20171103_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingestjob',
            old_name='apply_changes_retries',
            new_name='retries',
        ),
        migrations.RemoveField(
            model_name='ingestjob',
            name='normalized_data',
        ),
    ]
