# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import share.models.ingest


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0049_merge_20171103_1955'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sourceconfig',
            managers=[
                ('objects', share.models.ingest.SourceConfigManager('label')),
            ],
        ),
        migrations.RenameField(
            model_name='harvestjob',
            old_name='context',
            new_name='error_context',
        ),
        migrations.RenameField(
            model_name='ingestjob',
            old_name='context',
            new_name='error_context',
        ),
        migrations.AddField(
            model_name='harvestjob',
            name='claimed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='harvestjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvestjob',
            name='error_type',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='claimed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='error_type',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='retries',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='normalizeddata',
            name='ingest_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingested_normalized_data', to='share.IngestJob'),
        ),
    ]
