# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import share.models.ingest


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0050_auto_20171127_1632'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sourceconfig',
            managers=[
                ('objects', share.models.ingest.SourceConfigManager('label')),
            ],
        ),
        migrations.AddField(
            model_name='harvestjob',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
