# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0050_harvest_job_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatum',
            name='suid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='share.SourceUniqueIdentifier'),
        ),
    ]
