# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0051_auto_20180301_2032'),
        ('share', '0051_auto_20180319_2145'),
    ]

    operations = [
    ]
