# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-12-07 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0053_auto_20180419_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormattedMetadataRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_format', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('formatted_metadata', models.TextField()),
                ('suid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='formattedmetadatarecord',
            unique_together=set([('suid', 'record_format')]),
        ),
    ]
