# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-02-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0056_auto_20210217_1923'),
    ]

    operations = [
        # no changes in the database, just trying to disentangle the `ConcurrentIndex` concept
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='rawdatum',
                    name='share_rawda_no_outp_f0330f_idx',
                ),
                migrations.AddIndex(
                    model_name='rawdatum',
                    index=models.Index(fields=['no_output'], name='share_rawda_no_outp_f0330f_idx'),
                ),
            ],
        ),
    ]
