# Generated by Django 3.2.5 on 2022-12-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0061_ensure_auto_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconfig',
            name='harvester_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sourceconfig',
            name='transformer_key',
            field=models.TextField(null=True),
        ),
    ]
