# Generated by Django 3.2.5 on 2022-12-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0065_drop_harvester_transformer_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceconfig',
            name='harvester',
        ),
        migrations.RemoveField(
            model_name='sourceconfig',
            name='transformer',
        ),
        migrations.DeleteModel(
            name='Harvester',
        ),
        migrations.DeleteModel(
            name='Transformer',
        ),
    ]
