# Generated by Django 3.2.5 on 2022-12-22 17:49

from django.db import migrations, models
import share.models.fields
import share.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0066_drop_harvester_transformer_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizeddata',
            name='described_resource_uri',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizeddata',
            name='serialized_rdfgraph',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='rawdatum',
            name='contenttype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceuniqueidentifier',
            name='described_resource_pid',
            field=share.models.fields.ShareURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formattedmetadatarecord',
            name='record_format',
            field=models.TextField(choices=[('oai_dc', 'oai_dc'), ('sharev2_elastic', 'sharev2_elastic')]),
        ),
        migrations.AlterField(
            model_name='normalizeddata',
            name='data',
            field=share.models.fields.DateTimeAwareJSONField(decoder=share.models.fields.DateTimeAwareJSONDecoder, encoder=share.models.fields.DateTimeAwareJSONEncoder, null=True, validators=[share.models.validators.JSONLDValidator()]),
        ),
    ]
