# Generated by Django 3.2.5 on 2022-12-29 19:47
from django.db import migrations, models


def remove_extra_ingestjobs(apps, schema_editor):
    IngestJob = apps.get_model('share', 'IngestJob')
    deletable_ingestjob_qs = (
        IngestJob.objects
        .annotate(latest_ingestjob_id_for_suid=(
            IngestJob.objects
            .filter(suid=models.OuterRef('suid'))
            .order_by('-date_modified')
            .values('id')
            [:1]
        ))
        .exclude(id=models.F('latest_ingestjob_id_for_suid'))
    )
    deletable_ingestjob_qs.delete()


def fake_undo(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0067_rdf'),
    ]

    operations = [
        migrations.RunPython(remove_extra_ingestjobs, fake_undo),
    ]
