# Generated by Django 3.2.5 on 2022-12-22 14:39
import rdflib

from django.conf import settings
from django.db import migrations

from share.util.ingester import Ingester


def extract_term_descriptions(vocab_rdfgraph, vocab_uri):
    vocab_terms = vocab_rdfgraph.subjects(
        predicate=rdflib.RDFS.isDefinedBy,
        object=vocab_uri,
        unique=True,
    )
    for vocab_term in vocab_terms:
        yield vocab_term, vocab_rdfgraph.cbd(vocab_term)


def ingest_vocab_term(system_user, term_uri, term_description_rdfgraph):
    term_description = term_description_rdfgraph.serialize(format='turtle')
    Ingester(term_description, term_uri, 'text/turtle').as_user(system_user).ingest()


def load_dcterms(apps, schema_editor):
    ShareUser = apps.get_model('share', 'ShareUser')
    system_user = ShareUser.objects.get(username=settings.APPLICATION_USERNAME)
    with open('vocab/dublin_core_terms.ttl') as dcterms_file:
        dcterms_rdfgraph = rdflib.Graph().parse(file=dcterms_file)
    term_gen = extract_term_descriptions(dcterms_rdfgraph, 'http://purl.org/dc/terms/')
    for term_uri, term_description in term_gen:
        ingest_vocab_term(system_user, term_uri, term_description)


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0067_rdf'),
    ]

    operations = [
        migrations.RunPython(load_dcterms),
    ]
