# Generated by Django 3.2.5 on 2022-12-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0068_remove_extra_ingestjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestjob',
            name='suid',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ingest_job', to='share.sourceuniqueidentifier'),
        ),
        migrations.AlterUniqueTogether(
            name='ingestjob',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ingestjob',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='ingestjob',
            name='regulator_version',
        ),
        migrations.RemoveField(
            model_name='ingestjob',
            name='source_config',
        ),
        migrations.RemoveField(
            model_name='ingestjob',
            name='source_config_version',
        ),
        migrations.RemoveField(
            model_name='ingestjob',
            name='transformer_version',
        ),
    ]
