# Generated by Django 3.2.5 on 2022-12-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0068_dcterms_vocab'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconfig',
            name='rdfpush',
            field=models.BooleanField(default=False),
        ),
    ]
