# Generated by Django 3.2.5 on 2023-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0068_tidy_ingestjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatum',
            name='mediatype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
