# Generated by Django 3.2.5 on 2023-06-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0069_rawdatum_mediatype'),
        ('trove', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceuniqueidentifier',
            name='record_focus_piri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trove.persistentiri'),
        ),
        migrations.AlterField(
            model_name='formattedmetadatarecord',
            name='record_format',
            field=models.TextField(choices=[('oai_dc', 'oai_dc'), ('osfmap_jsonld', 'osfmap_jsonld'), ('sharev2_elastic', 'sharev2_elastic')]),
        ),
    ]
