# Generated by Django 3.2.5 on 2022-12-22 14:39
import rdflib

from django.conf import settings
from django.db import migrations

from share.push import ingest


def extract_term_descriptions(vocab_rdfgraph, vocab_uri):
    vocab_terms = vocab_rdfgraph.subjects(
        predicate=rdflib.RDFS.isDefinedBy,
        object=vocab_uri,
        unique=True,
    )
    for vocab_term in vocab_terms:
        yield vocab_term, vocab_rdfgraph.cbd(vocab_term)


def ingest_vocab_term(system_user, term_uri, term_description_rdfgraph):
    print(f'ingesting {term_uri}')
    suid = ingest.chew(
        datum=term_description_rdfgraph.serialize(format='turtle'),
        datum_identifier=str(term_uri),
        datum_contenttype='text/turtle',
        user=system_user,
    )
    ingest.digest(suid)


def load_dcterms(apps, schema_editor):
    ShareUser = apps.get_model('share', 'ShareUser')
    system_user = ShareUser.objects.get(username=settings.APPLICATION_USERNAME)
    with open('vocab/dublin_core_terms.ttl') as dcterms_file:
        dcterms_rdfgraph = rdflib.Graph().parse(file=dcterms_file)
    term_gen = extract_term_descriptions(dcterms_rdfgraph, rdflib.URIRef(rdflib.DCTERMS))
    for term_uri, term_description in term_gen:
        ingest_vocab_term(system_user, term_uri, term_description)


def fake_undo(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0069_tidy_ingestjob'),
    ]

    operations = [
        migrations.RunPython(load_dcterms, fake_undo),
    ]
