# Generated by Django 3.2.5 on 2023-06-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trove', '0001_initial'),
        ('share', '0069_rawdatum_mediatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceuniqueidentifier',
            name='resource_piri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='synonymous_suid_set', to='trove.persistentiri'),
        ),
    ]
