# Generated by Django 3.2.5 on 2023-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trove', '0001_initial'),
        ('share', '0069_rawdatum_mediatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceuniqueidentifier',
            name='record_focus_piri_set',
            field=models.ManyToManyField(related_name='_share_sourceuniqueidentifier_record_focus_piri_set_+', to='trove.PersistentIri'),
        ),
    ]
