# Generated by Django 3.2.5 on 2023-07-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0070_sourceuniqueidentifier_focus_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatorlog',
            name='ingest_job',
        ),
        migrations.DeleteModel(
            name='IngestJob',
        ),
        migrations.DeleteModel(
            name='RegulatorLog',
        ),
    ]
