# Generated by Django 3.2.5 on 2023-06-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0070_entrove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formattedmetadatarecord',
            name='record_format',
            field=models.TextField(choices=[('oai_dc', 'oai_dc'), ('sharev2_elastic', 'sharev2_elastic')]),
        ),
    ]
