# Generated by Django 3.2.5 on 2023-07-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0071_drop_ingestjob_regulatorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexbackfill',
            name='backfill_phase_index',
            field=models.IntegerField(default=0),
        ),
    ]
