# Generated by Django 3.2.5 on 2023-08-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0072_indexbackfill_backfill_phase_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexbackfill',
            name='backfill_phase_index',
        ),
    ]
