# Generated by Django 3.2.25 on 2024-09-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0073_remove_indexbackfill_backfill_phase_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceuniqueidentifier',
            name='is_supplementary',
            field=models.BooleanField(null=True),
        ),
    ]
