# Generated by Django 3.2.25 on 2024-10-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0074_sourceuniqueidentifier_is_supplementary'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatum',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='An (optional) date after which this datum is no longer valid.', null=True),
        ),
    ]
