# Generated by Django 3.2.25 on 2025-01-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0076_rawdatum_share_rawdatum_expiration_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexbackfill',
            old_name='specific_indexname',
            new_name='strategy_checksum',
        ),
    ]
