# Generated by Django 3.2.25 on 2025-05-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0077_big_cleanup_2025'),
        ('trove', '0008_no_raw_datum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawDatum',
        ),
    ]
